// exam-data.ts — Original quiz questions for QC (SAAQ) and ON (MTO)
// Questions are ORIGINAL, inspired by official handbooks — NOT copied.
// Sources: SAAQ "Conduire une moto", MTO "Motorcycle Handbook"
// Disclaimer: Not affiliated with SAAQ or MTO. Educational purposes only.

export type Province = 'qc' | 'on';
export type Category = 'rules' | 'safety' | 'gear' | 'skills' | 'signs' | 'licensing';

export interface Question {
  id: string;
  province: Province;
  category: Category;
  questionFr: string;
  questionEn: string;
  options: { fr: string; en: string }[];
  correctIndex: number;
  explanationFr: string;
  explanationEn: string;
}

export const questions: Question[] = [

  // ============================================================
  // QUÉBEC (SAAQ) — 50 questions
  // ============================================================

  // --- ROAD RULES / Règles de la route (10 questions) ---

  {
    id: 'qc-01',
    province: 'qc',
    category: 'rules',
    questionFr: 'Quelle distance minimale en secondes devez-vous maintenir derrière un véhicule ?',
    questionEn: 'What minimum following distance in seconds must you keep behind a vehicle?',
    options: [
      { fr: '1 seconde', en: '1 second' },
      { fr: '2 secondes', en: '2 seconds' },
      { fr: '3 secondes', en: '3 seconds' },
      { fr: '5 secondes', en: '5 seconds' },
    ],
    correctIndex: 2,
    explanationFr: 'La SAAQ recommande un minimum de 3 secondes. Choisissez un repère fixe. Quand le véhicule devant passe ce repère, comptez 3 secondes. En pluie, doublez cette distance.',
    explanationEn: 'SAAQ recommends a minimum of 3 seconds. Pick a fixed marker. When the vehicle ahead passes it, count 3 seconds. In rain, double this distance.',
  },
  {
    id: 'qc-02',
    province: 'qc',
    category: 'rules',
    questionFr: 'Quelle est la limite de vitesse dans une zone scolaire active au Québec ?',
    questionEn: 'What is the speed limit in an active school zone in Quebec?',
    options: [
      { fr: '30 km/h', en: '30 km/h' },
      { fr: '40 km/h', en: '40 km/h' },
      { fr: '50 km/h', en: '50 km/h' },
      { fr: '60 km/h', en: '60 km/h' },
    ],
    correctIndex: 0,
    explanationFr: 'Dans les zones scolaires actives (panneaux fluorescents), la limite est 30 km/h. Ces zones sont actives quand des écoliers sont présents, avant et après l\'école.',
    explanationEn: 'In active school zones (fluorescent signs), the limit is 30 km/h. These zones are active when children are present, before and after school.',
  },
  {
    id: 'qc-03',
    province: 'qc',
    category: 'rules',
    questionFr: 'Dans une zone de travaux, quelle limite de vitesse devez-vous respecter ?',
    questionEn: 'In a construction zone, what speed limit must you follow?',
    options: [
      { fr: '50 km/h en tout temps', en: '50 km/h at all times' },
      { fr: '60 km/h en tout temps', en: '60 km/h at all times' },
      { fr: 'Celle affichée sur les panneaux oranges', en: 'The speed shown on orange signs' },
      { fr: 'La même que sur la route normale', en: 'The same as the normal road' },
    ],
    correctIndex: 2,
    explanationFr: 'Dans les zones de travaux, respectez la limite affichée sur les panneaux oranges. Elle varie entre 60 et 70 km/h. Les amendes y sont doublées.',
    explanationEn: 'In construction zones, follow the limit on orange signs. It usually ranges from 60 to 70 km/h. Fines are doubled in these zones.',
  },
  {
    id: 'qc-04',
    province: 'qc',
    category: 'rules',
    questionFr: 'Est-il permis de rouler entre deux voies de voitures (lane splitting) au Québec ?',
    questionEn: 'Is riding between two lanes of cars (lane splitting) allowed in Quebec?',
    options: [
      { fr: 'Oui, si la vitesse est sous 30 km/h', en: 'Yes, if speed is under 30 km/h' },
      { fr: 'Non, c\'est strictement interdit', en: 'No, it is strictly forbidden' },
      { fr: 'Oui, seulement en cas d\'embouteillage', en: 'Yes, only in traffic jams' },
      { fr: 'Oui, sur autoroute à basse vitesse', en: 'Yes, on highways at low speed' },
    ],
    correctIndex: 1,
    explanationFr: 'Le lane splitting est interdit au Québec. Chaque moto doit occuper une voie complète. Circuler entre les voitures est dangereux et illégal.',
    explanationEn: 'Lane splitting is forbidden in Quebec. Each motorcycle must occupy a full lane. Riding between cars is dangerous and illegal.',
  },
  {
    id: 'qc-05',
    province: 'qc',
    category: 'rules',
    questionFr: 'À un arrêt à quatre directions, qui a priorité si deux véhicules arrivent en même temps ?',
    questionEn: 'At a four-way stop, who has priority when two vehicles arrive at the same time?',
    options: [
      { fr: 'Le véhicule à gauche', en: 'The vehicle on the left' },
      { fr: 'Le véhicule à droite', en: 'The vehicle on the right' },
      { fr: 'Le plus gros véhicule', en: 'The larger vehicle' },
      { fr: 'Le premier à klaxonner', en: 'The first to honk' },
    ],
    correctIndex: 1,
    explanationFr: 'Quand deux véhicules arrivent en même temps à un arrêt à quatre directions, celui à droite a la priorité. Cédez toujours au véhicule à votre droite.',
    explanationEn: 'When two vehicles arrive simultaneously at a four-way stop, the vehicle on the right has priority. Always yield to the vehicle on your right.',
  },
  {
    id: 'qc-06',
    province: 'qc',
    category: 'rules',
    questionFr: 'Sur une route avec deux voies dans le même sens, peut-on dépasser par la droite ?',
    questionEn: 'On a road with two lanes in the same direction, can you pass on the right?',
    options: [
      { fr: 'Oui, toujours permis', en: 'Yes, always allowed' },
      { fr: 'Non, jamais', en: 'No, never' },
      { fr: 'Oui, si la voie de droite est libre', en: 'Yes, if the right lane is clear' },
      { fr: 'Seulement sur autoroute', en: 'Only on highways' },
    ],
    correctIndex: 2,
    explanationFr: 'Dépasser par la droite est permis si la voie droite est libre. Cela s\'applique aux routes à plusieurs voies dans le même sens. Vérifiez toujours vos angles morts.',
    explanationEn: 'Passing on the right is allowed if the right lane is clear. This applies to roads with multiple same-direction lanes. Always check blind spots.',
  },
  {
    id: 'qc-07',
    province: 'qc',
    category: 'rules',
    questionFr: 'Quelle est la limite de vitesse par défaut dans une zone résidentielle au Québec ?',
    questionEn: 'What is the default speed limit in a residential area in Quebec?',
    options: [
      { fr: '30 km/h', en: '30 km/h' },
      { fr: '40 km/h', en: '40 km/h' },
      { fr: '50 km/h', en: '50 km/h' },
      { fr: '70 km/h', en: '70 km/h' },
    ],
    correctIndex: 2,
    explanationFr: 'La limite par défaut en zone résidentielle est 50 km/h, sauf indication contraire. Si un panneau de 30 km/h est affiché dans votre secteur, respectez-le.',
    explanationEn: 'The default limit in residential areas is 50 km/h unless otherwise posted. If a 30 km/h sign is posted in your area, respect it.',
  },
  {
    id: 'qc-08',
    province: 'qc',
    category: 'rules',
    questionFr: 'Deux motos peuvent-elles rouler côte à côte dans la même voie ?',
    questionEn: 'Can two motorcycles ride side by side in the same lane?',
    options: [
      { fr: 'Oui, toujours', en: 'Yes, always' },
      { fr: 'Non, c\'est interdit', en: 'No, it is prohibited' },
      { fr: 'Oui, sur autoroute seulement', en: 'Yes, on highways only' },
      { fr: 'Oui, si les deux conducteurs sont d\'accord', en: 'Yes, if both riders agree' },
    ],
    correctIndex: 1,
    explanationFr: 'Deux motos ne peuvent pas rouler côte à côte dans la même voie. Chaque moto doit occuper une voie entière. En groupe, roulez en quinconce dans la même voie.',
    explanationEn: 'Two motorcycles cannot ride side by side in the same lane. Each motorcycle must occupy a full lane. In a group, ride staggered within the same lane.',
  },
  {
    id: 'qc-09',
    province: 'qc',
    category: 'rules',
    questionFr: 'Il pleut fortement. Que devez-vous faire avec votre vitesse et distance de suivi ?',
    questionEn: 'It is raining hard. What should you do with your speed and following distance?',
    options: [
      { fr: 'Maintenir la vitesse normale, même distance', en: 'Keep normal speed and distance' },
      { fr: 'Réduire la vitesse et doubler la distance', en: 'Reduce speed and double the distance' },
      { fr: 'Accélérer pour sortir plus vite de la pluie', en: 'Accelerate to get out of the rain faster' },
      { fr: 'Seulement réduire la vitesse', en: 'Only reduce speed' },
    ],
    correctIndex: 1,
    explanationFr: 'Par temps pluvieux, réduisez votre vitesse et doublez votre distance de suivi. La chaussée mouillée augmente la distance de freinage et réduit la visibilité.',
    explanationEn: 'In rainy conditions, reduce speed and double your following distance. Wet roads increase braking distance and reduce visibility.',
  },
  {
    id: 'qc-10',
    province: 'qc',
    category: 'rules',
    questionFr: 'Vous approchez d\'un feu jaune. Que devez-vous faire ?',
    questionEn: 'You are approaching a yellow traffic light. What should you do?',
    options: [
      { fr: 'Accélérer pour passer avant le rouge', en: 'Accelerate to pass before red' },
      { fr: 'Freiner et vous arrêter si c\'est sécuritaire', en: 'Brake and stop if safely possible' },
      { fr: 'Maintenir votre vitesse', en: 'Maintain your speed' },
      { fr: 'Klaxonner et passer', en: 'Honk and continue' },
    ],
    correctIndex: 1,
    explanationFr: 'Un feu jaune signifie que le feu va passer au rouge. Freinez et arrêtez-vous si c\'est sécuritaire. N\'accélérez pas pour brûler le feu.',
    explanationEn: 'A yellow light means the light is about to turn red. Brake and stop if it is safe to do so. Never accelerate to run the light.',
  },

  // --- ROAD SIGNS / Signalisation routière (10 questions) ---

  {
    id: 'qc-11',
    province: 'qc',
    category: 'signs',
    questionFr: 'Un panneau jaune en losange avec un point d\'exclamation signifie quoi ?',
    questionEn: 'A yellow diamond sign with an exclamation mark means what?',
    options: [
      { fr: 'Arrêt obligatoire', en: 'Mandatory stop' },
      { fr: 'Danger ou condition inhabituelle à venir', en: 'Danger or unusual condition ahead' },
      { fr: 'Vitesse maximale', en: 'Maximum speed' },
      { fr: 'Zone de silence', en: 'Quiet zone' },
    ],
    correctIndex: 1,
    explanationFr: 'Les panneaux jaunes en losange sont des panneaux d\'avertissement. Un point d\'exclamation indique un danger ou une condition inhabituelle à venir. Ralentissez et soyez vigilant.',
    explanationEn: 'Yellow diamond signs are warning signs. An exclamation mark means danger or an unusual condition ahead. Slow down and stay alert.',
  },
  {
    id: 'qc-12',
    province: 'qc',
    category: 'signs',
    questionFr: 'Vous voyez un panneau rouge octogonal avec "ARRÊT". Que devez-vous faire ?',
    questionEn: 'You see a red octagonal sign that says "STOP". What must you do?',
    options: [
      { fr: 'Ralentir et céder le passage', en: 'Slow down and yield' },
      { fr: 'Immobiliser complètement votre moto', en: 'Come to a complete stop' },
      { fr: 'Ralentir à 20 km/h et passer', en: 'Slow to 20 km/h and continue' },
      { fr: 'Klaxonner et passer', en: 'Honk and continue' },
    ],
    correctIndex: 1,
    explanationFr: 'À un panneau d\'arrêt, immobilisez-vous complètement. Les deux roues doivent s\'arrêter. Ensuite, cédez le passage avant de repartir.',
    explanationEn: 'At a stop sign, come to a complete stop. Both wheels must stop. Then yield before proceeding.',
  },
  {
    id: 'qc-13',
    province: 'qc',
    category: 'signs',
    questionFr: 'Un triangle rouge pointant vers le bas indique quoi sur une route ?',
    questionEn: 'A downward-pointing red triangle on a road indicates what?',
    options: [
      { fr: 'Zone de dépassement interdit', en: 'No passing zone' },
      { fr: 'Céder le passage', en: 'Yield the right of way' },
      { fr: 'Zone scolaire', en: 'School zone' },
      { fr: 'Voie réservée aux camions', en: 'Truck only lane' },
    ],
    correctIndex: 1,
    explanationFr: 'Le triangle rouge pointant vers le bas est le panneau de cédez le passage. Ralentissez et laissez passer les autres usagers. Arrêtez si nécessaire.',
    explanationEn: 'The downward-pointing red triangle is the yield sign. Slow down and let other road users pass. Stop if necessary.',
  },
  {
    id: 'qc-14',
    province: 'qc',
    category: 'signs',
    questionFr: 'Des flèches chevrons jaunes sur fond noir indiquent quoi sur la route ?',
    questionEn: 'Yellow chevron arrows on a black background on the road indicate what?',
    options: [
      { fr: 'Une voie à sens unique', en: 'A one-way lane' },
      { fr: 'Un virage serré à venir', en: 'A sharp curve ahead' },
      { fr: 'Une zone de construction', en: 'A construction zone' },
      { fr: 'Une entrée d\'autoroute', en: 'A highway entrance' },
    ],
    correctIndex: 1,
    explanationFr: 'Les chevrons jaunes sur fond noir signalent un virage serré à venir. Ralentissez avant le virage, pas pendant. Ces panneaux se trouvent souvent sur les courbes de montagne.',
    explanationEn: 'Yellow chevrons on a black background warn of a sharp curve ahead. Slow down before the curve, not during. These signs are common on mountain roads.',
  },
  {
    id: 'qc-15',
    province: 'qc',
    category: 'signs',
    questionFr: 'Un panneau en forme de X avec deux barres croisées signifie quoi ?',
    questionEn: 'An X-shaped sign with two crossed bars means what?',
    options: [
      { fr: 'Intersection à risque élevé', en: 'High-risk intersection' },
      { fr: 'Passage à niveau ferroviaire', en: 'Railway crossing' },
      { fr: 'Zone de jeux', en: 'Play zone' },
      { fr: 'Sens interdit', en: 'No entry' },
    ],
    correctIndex: 1,
    explanationFr: 'Le panneau en X avec deux barres croisées indique un passage à niveau ferroviaire. Approchez lentement, regardez des deux côtés. Un train est prioritaire sur tout.',
    explanationEn: 'The X sign with two crossed bars indicates a railway crossing. Approach slowly and look both ways. A train has priority over everything.',
  },
  {
    id: 'qc-16',
    province: 'qc',
    category: 'signs',
    questionFr: 'Des panneaux oranges sur la route signalent quoi en général ?',
    questionEn: 'Orange signs on the road generally indicate what?',
    options: [
      { fr: 'Des zones scolaires', en: 'School zones' },
      { fr: 'Des zones de travaux ou de construction', en: 'Work or construction zones' },
      { fr: 'Des zones touristiques', en: 'Tourist zones' },
      { fr: 'Des zones de silence obligatoire', en: 'Mandatory quiet zones' },
    ],
    correctIndex: 1,
    explanationFr: 'Les panneaux oranges signalent des zones de travaux ou de construction. Ralentissez et soyez vigilant. Les amendes sont doublées dans ces zones au Québec.',
    explanationEn: 'Orange signs indicate construction or work zones. Slow down and stay alert. Fines are doubled in these zones in Quebec.',
  },
  {
    id: 'qc-17',
    province: 'qc',
    category: 'signs',
    questionFr: 'Un panneau blanc rectangulaire avec un chiffre en noir indique quoi ?',
    questionEn: 'A white rectangular sign with a black number indicates what?',
    options: [
      { fr: 'La vitesse recommandée', en: 'The recommended speed' },
      { fr: 'La limite de vitesse maximale obligatoire', en: 'The mandatory maximum speed limit' },
      { fr: 'La vitesse minimale', en: 'The minimum speed' },
      { fr: 'La vitesse en zone scolaire seulement', en: 'The school zone speed only' },
    ],
    correctIndex: 1,
    explanationFr: 'Les panneaux de vitesse blancs rectangulaires indiquent la limite maximale obligatoire. Vous ne pouvez pas légalement dépasser ce chiffre sur cette route.',
    explanationEn: 'White rectangular speed signs indicate the mandatory maximum limit. You cannot legally exceed this number on that road.',
  },
  {
    id: 'qc-18',
    province: 'qc',
    category: 'signs',
    questionFr: 'Que signifie une double ligne jaune continue au centre de la chaussée ?',
    questionEn: 'What does a double solid yellow center line on the road mean?',
    options: [
      { fr: 'Dépassement interdit des deux côtés', en: 'No passing from either side' },
      { fr: 'Dépassement permis des deux côtés', en: 'Passing allowed from either side' },
      { fr: 'Voie réservée aux vélos', en: 'Reserved lane for bikes' },
      { fr: 'Marquage du centre de la route seulement', en: 'Road center marking only' },
    ],
    correctIndex: 0,
    explanationFr: 'Une double ligne jaune continue interdit le dépassement dans les deux sens. Ne franchissez jamais ces lignes pour dépasser. C\'est très dangereux et illégal.',
    explanationEn: 'A double solid yellow line prohibits passing in both directions. Never cross these lines to pass. It is very dangerous and illegal.',
  },
  {
    id: 'qc-19',
    province: 'qc',
    category: 'signs',
    questionFr: 'Une ligne blanche discontinue entre deux voies dans le même sens signifie quoi ?',
    questionEn: 'A dashed white line between two same-direction lanes means what?',
    options: [
      { fr: 'Changement de voie et dépassement permis', en: 'Lane change and passing allowed' },
      { fr: 'Séparation permanente des voies', en: 'Permanent lane separation' },
      { fr: 'Voie de dépassement seulement', en: 'Passing lane only' },
      { fr: 'Voie réservée aux motos', en: 'Motorcycle-only lane' },
    ],
    correctIndex: 0,
    explanationFr: 'Une ligne blanche discontinue permet les changements de voie et les dépassements. Vérifiez toujours vos angles morts avant de changer de voie.',
    explanationEn: 'A dashed white line allows lane changes and passing. Always check your blind spots before changing lanes.',
  },
  {
    id: 'qc-20',
    province: 'qc',
    category: 'signs',
    questionFr: 'Un panneau avec une silhouette de piéton dans un triangle jaune vous avertit de quoi ?',
    questionEn: 'A yellow triangle sign showing a pedestrian silhouette warns you of what?',
    options: [
      { fr: 'Une traversée de piétons à venir', en: 'A pedestrian crossing ahead' },
      { fr: 'Un arrêt pour piétons obligatoire', en: 'A mandatory stop for pedestrians' },
      { fr: 'Une voie piétonne seulement', en: 'A pedestrian-only lane' },
      { fr: 'Une zone de parc', en: 'A park zone' },
    ],
    correctIndex: 0,
    explanationFr: 'Ce panneau d\'avertissement signale une traversée de piétons à venir. Ralentissez et cédez le passage. Les piétons ont priorité sur les passages cloutés.',
    explanationEn: 'This warning sign indicates a pedestrian crossing ahead. Slow down and yield. Pedestrians have priority at marked crosswalks.',
  },

  // --- MOTORCYCLE SAFETY / Sécurité et technique (10 questions) ---

  {
    id: 'qc-21',
    province: 'qc',
    category: 'safety',
    questionFr: 'En freinage d\'urgence, comment utilise-t-on les freins ?',
    questionEn: 'In emergency braking, how should you use the brakes?',
    options: [
      { fr: 'Frein avant seulement, fort et rapide', en: 'Front brake only, hard and fast' },
      { fr: 'Frein arrière seulement pour éviter le cabrage', en: 'Rear brake only to avoid a wheelie' },
      { fr: 'Les deux freins progressivement en même temps', en: 'Both brakes progressively at the same time' },
      { fr: 'Couper les gaz et attendre', en: 'Cut the throttle and wait' },
    ],
    correctIndex: 2,
    explanationFr: 'En urgence, appliquez les deux freins progressivement en même temps. Le frein avant donne 70 à 80% de la puissance de freinage. Serrez fort mais évitez de bloquer les roues.',
    explanationEn: 'In an emergency, apply both brakes progressively at the same time. The front brake provides 70 to 80% of stopping power. Squeeze hard but avoid locking the wheels.',
  },
  {
    id: 'qc-22',
    province: 'qc',
    category: 'safety',
    questionFr: 'Pourquoi le phare d\'une moto doit-il rester allumé même en plein jour ?',
    questionEn: 'Why should a motorcycle headlight stay on even in full daylight?',
    options: [
      { fr: 'C\'est obligatoire par la loi seulement', en: 'It is required by law only' },
      { fr: 'Cela améliore la visibilité pour les autres conducteurs seulement', en: 'It improves visibility to other drivers only' },
      { fr: 'C\'est obligatoire et améliore votre visibilité', en: 'It is mandatory and improves your visibility' },
      { fr: 'Cela économise la batterie', en: 'It saves the battery' },
    ],
    correctIndex: 2,
    explanationFr: 'Le phare de jour est obligatoire et améliore votre visibilité. Les motos sont petites et difficiles à voir. Un phare allumé attire l\'attention des automobilistes.',
    explanationEn: 'The daytime headlight is mandatory and improves your visibility. Motorcycles are small and hard to see. A lit headlight attracts the attention of car drivers.',
  },
  {
    id: 'qc-23',
    province: 'qc',
    category: 'safety',
    questionFr: 'Pour un virage à droite, où dans la voie devez-vous vous positionner avant d\'entrer ?',
    questionEn: 'For a right-hand curve, where in your lane should you position before entering?',
    options: [
      { fr: 'À droite de la voie', en: 'On the right side of the lane' },
      { fr: 'Au centre de la voie', en: 'In the center of the lane' },
      { fr: 'À gauche de la voie', en: 'On the left side of the lane' },
      { fr: 'N\'importe où dans la voie', en: 'Anywhere in the lane' },
    ],
    correctIndex: 2,
    explanationFr: 'Pour un virage à droite, positionnez-vous à gauche de votre voie avant d\'entrer. Cela vous donne une meilleure vue du virage et plus d\'espace pour corriger.',
    explanationEn: 'For a right curve, position yourself on the left side of your lane before entering. This gives you a better view of the curve and more room to correct.',
  },
  {
    id: 'qc-24',
    province: 'qc',
    category: 'safety',
    questionFr: 'Sur une route mouillée, comment ajustez-vous votre conduite en virage ?',
    questionEn: 'On a wet road, how do you adjust your riding through a curve?',
    options: [
      { fr: 'Pencher plus fort pour contrebalancer le glissement', en: 'Lean harder to counterbalance sliding' },
      { fr: 'Réduire la vitesse avant et éviter les freinages brusques', en: 'Reduce speed before and avoid sharp braking' },
      { fr: 'Accélérer pour traverser plus vite', en: 'Accelerate to get through faster' },
      { fr: 'Aucun changement nécessaire', en: 'No changes needed' },
    ],
    correctIndex: 1,
    explanationFr: 'Sur route mouillée, réduisez votre vitesse avant le virage. Évitez de freiner ou d\'accélérer brusquement en plein virage. L\'adhérence est réduite sur chaussée mouillée.',
    explanationEn: 'On wet roads, reduce speed before the curve. Avoid sudden braking or acceleration mid-curve. Grip is reduced on a wet surface.',
  },
  {
    id: 'qc-25',
    province: 'qc',
    category: 'safety',
    questionFr: 'Quel effet le port du casque a-t-il selon les données de sécurité routière ?',
    questionEn: 'What effect does wearing a helmet have according to road safety data?',
    options: [
      { fr: 'Il réduit le risque de décès d\'environ 10%', en: 'It reduces death risk by about 10%' },
      { fr: 'Il réduit le risque de blessures à la tête d\'environ 69%', en: 'It reduces head injury risk by about 69%' },
      { fr: 'Il n\'a pas d\'effet prouvé', en: 'It has no proven effect' },
      { fr: 'Il réduit seulement les blessures mineures', en: 'It only reduces minor injuries' },
    ],
    correctIndex: 1,
    explanationFr: 'Les études montrent que le casque réduit le risque de blessures à la tête de 69% et le risque de décès de 42%. C\'est l\'équipement le plus important du motocycliste.',
    explanationEn: 'Studies show helmets reduce head injury risk by 69% and death risk by 42%. It is the most important piece of equipment for a motorcyclist.',
  },
  {
    id: 'qc-26',
    province: 'qc',
    category: 'safety',
    questionFr: 'Quel type de certification un casque doit-il avoir pour être considéré sécuritaire ?',
    questionEn: 'What certification should a helmet carry to be considered safe?',
    options: [
      { fr: 'N\'importe quelle marque connue suffit', en: 'Any well-known brand is sufficient' },
      { fr: 'DOT, ECE 22.06 ou Snell', en: 'DOT, ECE 22.06 or Snell' },
      { fr: 'La certification SAAQ uniquement', en: 'SAAQ certification only' },
      { fr: 'Aucune certification requise', en: 'No certification required' },
    ],
    correctIndex: 1,
    explanationFr: 'Cherchez les certifications DOT (américaine), ECE 22.06 (européenne) ou Snell (privée). Ces certifications garantissent que le casque a passé des tests de choc rigoureux.',
    explanationEn: 'Look for DOT (American), ECE 22.06 (European) or Snell (private) certifications. These guarantee the helmet passed rigorous impact tests.',
  },
  {
    id: 'qc-27',
    province: 'qc',
    category: 'safety',
    questionFr: 'Vous conduisez depuis 3 heures sans pause. Que devez-vous faire ?',
    questionEn: 'You have been riding for 3 hours without a break. What should you do?',
    options: [
      { fr: 'Ouvrir votre visière pour rester éveillé', en: 'Open your visor to stay awake' },
      { fr: 'S\'arrêter, s\'étirer et se reposer', en: 'Stop, stretch, and rest' },
      { fr: 'Boire du café et continuer', en: 'Drink coffee and keep going' },
      { fr: 'Augmenter la vitesse pour arriver plus vite', en: 'Increase speed to arrive faster' },
    ],
    correctIndex: 1,
    explanationFr: 'La fatigue est dangereuse. Arrêtez-vous toutes les 2 heures pour vous étirer et vous reposer. La fatigue ralentit vos réflexes autant que l\'alcool.',
    explanationEn: 'Fatigue is dangerous. Stop every 2 hours to stretch and rest. Fatigue slows your reflexes as much as alcohol does.',
  },
  {
    id: 'qc-28',
    province: 'qc',
    category: 'safety',
    questionFr: 'Quel frein est le plus efficace pour arrêter rapidement une moto en ligne droite ?',
    questionEn: 'Which brake is most effective for stopping a motorcycle quickly in a straight line?',
    options: [
      { fr: 'Le frein arrière, car il stabilise la moto', en: 'The rear brake, because it stabilizes the motorcycle' },
      { fr: 'Le frein avant, car il produit plus de force d\'arrêt', en: 'The front brake, because it produces more stopping force' },
      { fr: 'Les deux freins sont également efficaces', en: 'Both brakes are equally effective' },
      { fr: 'Couper les gaz uniquement', en: 'Cut the throttle only' },
    ],
    correctIndex: 1,
    explanationFr: 'Le frein avant est responsable de 70 à 80% de la puissance de freinage. En urgence, utilisez les deux freins, mais le frein avant fait le plus grand effort.',
    explanationEn: 'The front brake provides 70 to 80% of braking power. In an emergency, use both brakes, but the front brake does most of the work.',
  },
  {
    id: 'qc-29',
    province: 'qc',
    category: 'safety',
    questionFr: 'La nuit, pourquoi ne faut-il pas rouler plus vite que la portée de votre phare ?',
    questionEn: 'At night, why should your speed not exceed the reach of your headlight?',
    options: [
      { fr: 'Pour économiser de l\'essence', en: 'To save fuel' },
      { fr: 'Pour pouvoir vous arrêter avant un obstacle qui surgit dans le noir', en: 'To be able to stop before an obstacle that appears in the dark' },
      { fr: 'C\'est une règle arbitraire', en: 'It is an arbitrary rule' },
      { fr: 'Les phares ne servent qu\'à être vu des autres', en: 'Headlights are only to be seen by others' },
    ],
    correctIndex: 1,
    explanationFr: 'Conduire plus vite que votre phare signifie que vous ne pouvez pas vous arrêter avant un obstacle dans le noir. Si quelque chose surgit, vous n\'avez pas le temps de réagir.',
    explanationEn: 'Overdriving your headlight means you cannot stop before an obstacle in the dark. If something appears, you do not have time to react.',
  },
  {
    id: 'qc-30',
    province: 'qc',
    category: 'safety',
    questionFr: 'Pour initier un virage à haute vitesse, quelle technique de direction utilisez-vous ?',
    questionEn: 'To initiate a turn at higher speed, what steering technique do you use?',
    options: [
      { fr: 'Tourner le guidon dans le sens du virage', en: 'Turn the handlebar toward the curve' },
      { fr: 'Appuyer sur le guidon du côté du virage (contre-braquage)', en: 'Push the handlebar on the curve side (counter-steering)' },
      { fr: 'Déplacer le poids du corps seulement', en: 'Shift body weight only' },
      { fr: 'Utiliser les freins pour tourner', en: 'Use the brakes to turn' },
    ],
    correctIndex: 1,
    explanationFr: 'Le contre-braquage : pour tourner à droite, poussez légèrement sur le guidon droit. La moto se penche à droite et tourne. C\'est la technique naturelle au-delà de 25 km/h.',
    explanationEn: 'Counter-steering: to turn right, push lightly on the right handlebar. The motorcycle leans right and turns. This is the natural technique above 25 km/h.',
  },

  // --- QUEBEC LAW / Loi québécoise et SAAQ (10 questions) ---

  {
    id: 'qc-31',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Quel est le taux d\'alcoolémie maximal autorisé avec un permis probatoire de classe 6 ?',
    questionEn: 'What is the maximum blood alcohol level allowed with a probationary Class 6 license?',
    options: [
      { fr: '0,08%', en: '0.08%' },
      { fr: '0,05%', en: '0.05%' },
      { fr: '0,02%', en: '0.02%' },
      { fr: '0,00% — zéro alcool', en: '0.00% — zero alcohol' },
    ],
    correctIndex: 3,
    explanationFr: 'Avec un permis probatoire de classe 6, le taux d\'alcool doit être de 0,00%. Aucune consommation n\'est tolérée. Cela s\'applique aussi aux drogues qui affectent les capacités.',
    explanationEn: 'With a probationary Class 6 license, blood alcohol must be 0.00%. No alcohol is tolerated. This also applies to drugs that impair ability.',
  },
  {
    id: 'qc-32',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Au Québec, quel est l\'âge minimal pour obtenir un permis d\'apprenti de classe 6 ?',
    questionEn: 'In Quebec, what is the minimum age to get a Class 6 learner\'s license?',
    options: [
      { fr: '14 ans', en: '14 years old' },
      { fr: '16 ans', en: '16 years old' },
      { fr: '17 ans', en: '17 years old' },
      { fr: '18 ans', en: '18 years old' },
    ],
    correctIndex: 1,
    explanationFr: 'Au Québec, vous pouvez obtenir le permis d\'apprenti conducteur de classe 6 dès 16 ans. Vous devez d\'abord réussir l\'examen théorique à la SAAQ.',
    explanationEn: 'In Quebec, you can get the Class 6 learner\'s license at age 16. You must first pass the theory exam at the SAAQ.',
  },
  {
    id: 'qc-33',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Un motocycliste avec permis probatoire peut-il transporter un passager les 6 premiers mois ?',
    questionEn: 'Can a probationary motorcycle rider carry a passenger in the first 6 months?',
    options: [
      { fr: 'Oui, sans restriction', en: 'Yes, without restriction' },
      { fr: 'Oui, si le passager porte un casque', en: 'Yes, if the passenger wears a helmet' },
      { fr: 'Non, c\'est interdit pendant les 6 premiers mois', en: 'No, it is forbidden during the first 6 months' },
      { fr: 'Seulement sur les routes secondaires', en: 'Only on secondary roads' },
    ],
    correctIndex: 2,
    explanationFr: 'Les 6 premiers mois du permis probatoire, il est interdit de transporter un passager. Cette restriction vous laisse le temps de maîtriser la moto seul.',
    explanationEn: 'During the first 6 months of a probationary license, carrying a passenger is forbidden. This gives you time to master the motorcycle alone.',
  },
  {
    id: 'qc-34',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Utiliser un cellulaire tenu à la main en conduisant une moto est-il permis ?',
    questionEn: 'Is using a handheld cell phone while riding a motorcycle permitted?',
    options: [
      { fr: 'Oui, en mode mains libres seulement', en: 'Yes, in hands-free mode only' },
      { fr: 'Non, c\'est strictement interdit', en: 'No, it is strictly forbidden' },
      { fr: 'Oui, si vous êtes arrêté à un feu rouge', en: 'Yes, if stopped at a red light' },
      { fr: 'Oui, pour les appels d\'urgence seulement', en: 'Yes, for emergency calls only' },
    ],
    correctIndex: 1,
    explanationFr: 'L\'utilisation d\'un téléphone tenu à la main est strictement interdite en moto. Une amende importante s\'applique, ainsi que des points d\'inaptitude.',
    explanationEn: 'Using a handheld phone while riding is strictly forbidden. A significant fine and demerit points apply.',
  },
  {
    id: 'qc-35',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Combien de points d\'inaptitude pour un excès de vitesse de 21 à 30 km/h ?',
    questionEn: 'How many demerit points for speeding 21 to 30 km/h over the limit?',
    options: [
      { fr: '2 points', en: '2 points' },
      { fr: '3 points', en: '3 points' },
      { fr: '4 points', en: '4 points' },
      { fr: '5 points', en: '5 points' },
    ],
    correctIndex: 1,
    explanationFr: 'Un excès de vitesse de 21 à 30 km/h entraîne 3 points d\'inaptitude. Atteindre 15 points en 2 ans entraîne la suspension du permis de conduire.',
    explanationEn: 'Speeding 21 to 30 km/h over the limit results in 3 demerit points. Reaching 15 points in 2 years leads to license suspension.',
  },
  {
    id: 'qc-36',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Votre moto doit-elle être assurée pour circuler légalement sur la route au Québec ?',
    questionEn: 'Must your motorcycle be insured to legally ride on Quebec roads?',
    options: [
      { fr: 'Non, l\'assurance est optionnelle', en: 'No, insurance is optional' },
      { fr: 'Oui, l\'assurance responsabilité civile est obligatoire', en: 'Yes, civil liability insurance is mandatory' },
      { fr: 'Seulement si la moto vaut plus de 5 000 $', en: 'Only if the motorcycle is worth more than $5,000' },
      { fr: 'Seulement sur autoroute', en: 'Only on highways' },
    ],
    correctIndex: 1,
    explanationFr: 'L\'assurance responsabilité civile est obligatoire au Québec pour tout véhicule motorisé. Elle couvre les dommages causés aux autres. La SAAQ couvre les blessures corporelles.',
    explanationEn: 'Civil liability insurance is mandatory in Quebec for all motorized vehicles. It covers damage caused to others. The SAAQ covers bodily injuries.',
  },
  {
    id: 'qc-37',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Le phare de votre moto doit-il être allumé le jour au Québec ?',
    questionEn: 'Must your motorcycle headlight be on during the day in Quebec?',
    options: [
      { fr: 'Non, seulement après le coucher du soleil', en: 'No, only after sunset' },
      { fr: 'Oui, il est obligatoire jour et nuit', en: 'Yes, it is mandatory day and night' },
      { fr: 'Seulement par mauvais temps', en: 'Only in bad weather' },
      { fr: 'Seulement sur autoroute', en: 'Only on highways' },
    ],
    correctIndex: 1,
    explanationFr: 'Au Québec, le phare de moto doit être allumé en tout temps, jour et nuit. C\'est obligatoire par la loi et améliore votre visibilité pour les autres conducteurs.',
    explanationEn: 'In Quebec, the motorcycle headlight must be on at all times, day and night. It is legally mandatory and improves your visibility to other drivers.',
  },
  {
    id: 'qc-38',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Votre moto doit-elle obligatoirement avoir des rétroviseurs pour circuler légalement ?',
    questionEn: 'Must your motorcycle legally have mirrors to ride on the road?',
    options: [
      { fr: 'Non, les miroirs sont optionnels', en: 'No, mirrors are optional' },
      { fr: 'Oui, un rétroviseur gauche au minimum', en: 'Yes, at least one left mirror' },
      { fr: 'Oui, deux rétroviseurs sont obligatoires', en: 'Yes, two mirrors are required' },
      { fr: 'Seulement sur les routes à grande vitesse', en: 'Only on high-speed roads' },
    ],
    correctIndex: 2,
    explanationFr: 'Au Québec, les motos doivent avoir deux rétroviseurs pour circuler légalement. Les rétroviseurs sont essentiels pour surveiller la circulation derrière vous.',
    explanationEn: 'In Quebec, motorcycles must have two mirrors to ride legally. Mirrors are essential for monitoring traffic behind you.',
  },
  {
    id: 'qc-39',
    province: 'qc',
    category: 'licensing',
    questionFr: 'La classe 6R au Québec autorise la conduite de quels types de motos ?',
    questionEn: 'Class 6R in Quebec authorizes riding which types of motorcycles?',
    options: [
      { fr: 'Toutes les motos sans restriction', en: 'All motorcycles without restriction' },
      { fr: 'Motos de moins de 50 cylindrées', en: 'Motorcycles under 50cc' },
      { fr: 'Motos avec un rapport puissance/poids restreint', en: 'Motorcycles with a restricted power-to-weight ratio' },
      { fr: 'Uniquement les scooters et motos électriques', en: 'Scooters and electric motorcycles only' },
    ],
    correctIndex: 2,
    explanationFr: 'La classe 6R (R pour Restreint) limite les nouveaux conducteurs à des motos à rapport puissance/poids restreint. Après 24 mois, vous pouvez demander la classe 6A sans restriction.',
    explanationEn: 'Class 6R (R for Restricted) limits new riders to motorcycles with a restricted power-to-weight ratio. After 24 months, you can apply for unrestricted Class 6A.',
  },
  {
    id: 'qc-40',
    province: 'qc',
    category: 'licensing',
    questionFr: 'Conduire sans casque homologué au Québec est passible de quoi ?',
    questionEn: 'Riding without an approved helmet in Quebec is punishable by what?',
    options: [
      { fr: 'Un avertissement seulement', en: 'A warning only' },
      { fr: 'Une amende et des points d\'inaptitude', en: 'A fine and demerit points' },
      { fr: 'Une suspension immédiate du permis', en: 'An immediate license suspension' },
      { fr: 'Rien, c\'est un choix personnel', en: 'Nothing, it is a personal choice' },
    ],
    correctIndex: 1,
    explanationFr: 'Conduire sans casque homologué entraîne une amende et des points d\'inaptitude. Le casque est obligatoire pour le conducteur et le passager en tout temps au Québec.',
    explanationEn: 'Riding without an approved helmet results in a fine and demerit points. A helmet is mandatory for both rider and passenger at all times in Quebec.',
  },

  // --- RIDING SCENARIOS / Scénarios de conduite (10 questions) ---

  {
    id: 'qc-41',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous approchez des rails de train qui traversent la route en diagonale. Que faites-vous ?',
    questionEn: 'You approach train tracks crossing the road diagonally. What do you do?',
    options: [
      { fr: 'Les traverser le plus vite possible', en: 'Cross them as fast as possible' },
      { fr: 'Repositionner la moto pour traverser à angle droit', en: 'Reposition the motorcycle to cross at a right angle' },
      { fr: 'Les traverser en parallèle pour plus de stabilité', en: 'Cross them parallel for more stability' },
      { fr: 'Freiner fort avant et accélérer en traversant', en: 'Brake hard before and accelerate while crossing' },
    ],
    correctIndex: 1,
    explanationFr: 'Repositionnez-vous dans votre voie pour traverser les rails à 90 degrés. Une roue coincée dans un rail en diagonale peut vous faire chuter. Traversez lentement en ligne droite.',
    explanationEn: 'Reposition in your lane to cross the tracks at 90 degrees. A wheel caught in a diagonal rail can cause a fall. Cross slowly and in a straight line.',
  },
  {
    id: 'qc-42',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous prenez un virage et apercevez du gravier sur la chaussée. Que faites-vous ?',
    questionEn: 'You are taking a curve and suddenly see gravel on the road. What do you do?',
    options: [
      { fr: 'Freiner brusquement pour vous arrêter', en: 'Brake sharply to stop' },
      { fr: 'Regarder la sortie du virage et maintenir une trajectoire régulière', en: 'Look toward the curve exit and maintain a steady path' },
      { fr: 'Contre-braquer brusquement pour éviter le gravier', en: 'Counter-steer sharply to avoid the gravel' },
      { fr: 'Accélérer pour traverser la zone rapidement', en: 'Accelerate to get through quickly' },
    ],
    correctIndex: 1,
    explanationFr: 'Sur gravier, évitez les réactions brusques. Regardez la sortie du virage, maintenez une trajectoire régulière et gardez votre vitesse stable. Les mouvements brusques causent les chutes.',
    explanationEn: 'On gravel, avoid sudden reactions. Look toward the exit, maintain a steady path, and keep your speed stable. Sudden movements cause falls.',
  },
  {
    id: 'qc-43',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous roulez derrière un gros camion. Où devez-vous vous positionner dans votre voie ?',
    questionEn: 'You are riding behind a large truck. Where should you position yourself in your lane?',
    options: [
      { fr: 'Au centre, directement derrière le camion', en: 'In the center, directly behind the truck' },
      { fr: 'Décalé à gauche ou à droite pour voir devant et être vu', en: 'Offset left or right to see ahead and be seen' },
      { fr: 'Aussi près que possible pour profiter du courant d\'air', en: 'As close as possible to draft the truck' },
      { fr: 'À l\'extrême droite de votre voie', en: 'On the far right of your lane' },
    ],
    correctIndex: 1,
    explanationFr: 'Derrière un camion, décalez-vous à gauche ou à droite. Cela vous permet de voir devant et d\'être visible du camionneur. Évitez la zone de débris projetés derrière le camion.',
    explanationEn: 'Behind a truck, offset left or right. This lets you see farther ahead and be visible to the truck driver. Avoid the debris zone directly behind the truck.',
  },
  {
    id: 'qc-44',
    province: 'qc',
    category: 'skills',
    questionFr: 'Un conducteur tourne à gauche devant vous à une intersection sans vous avoir vu. Que faites-vous ?',
    questionEn: 'A driver turns left in front of you at an intersection without seeing you. What do you do?',
    options: [
      { fr: 'Klaxonner et accélérer', en: 'Honk and accelerate' },
      { fr: 'Freiner des deux freins et chercher une sortie de secours', en: 'Brake with both brakes and look for an escape route' },
      { fr: 'Virer brusquement à gauche', en: 'Swerve sharply left' },
      { fr: 'Fermer les yeux et freiner fort', en: 'Close your eyes and brake hard' },
    ],
    correctIndex: 1,
    explanationFr: 'C\'est le scénario le plus meurtrier pour les motocyclistes. Freinez des deux freins progressivement, cherchez une sortie de secours, et klaxonnez pour attirer l\'attention.',
    explanationEn: 'This is the deadliest scenario for motorcyclists. Brake progressively with both brakes, look for an escape route, and honk to draw attention.',
  },
  {
    id: 'qc-45',
    province: 'qc',
    category: 'skills',
    questionFr: 'Sur l\'autoroute, une voiture vous coupe et freine brusquement devant vous. Que faites-vous ?',
    questionEn: 'On the highway, a car cuts you off and brakes sharply. What do you do?',
    options: [
      { fr: 'Freiner brusquement et klaxonner', en: 'Brake sharply and honk' },
      { fr: 'Freiner progressivement et vous décaler latéralement si possible', en: 'Brake progressively and shift laterally if possible' },
      { fr: 'Accélérer pour le dépasser rapidement', en: 'Accelerate to pass quickly' },
      { fr: 'Utiliser uniquement le frein arrière pour ne pas cabrer', en: 'Use rear brake only to avoid a stoppie' },
    ],
    correctIndex: 1,
    explanationFr: 'Freinez progressivement des deux freins. Si vous avez de l\'espace, décalez-vous dans votre voie pour augmenter la distance. Restez calme et concentré sur votre sortie.',
    explanationEn: 'Brake progressively with both brakes. If you have space, shift laterally to increase distance. Stay calm and focused on your escape route.',
  },
  {
    id: 'qc-46',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous roulez en groupe sur l\'autoroute. Quelle formation est la plus sécuritaire ?',
    questionEn: 'You are riding in a group on the highway. Which formation is safest?',
    options: [
      { fr: 'En colonne simple, tous derrière le même point', en: 'Single file, all behind the same point' },
      { fr: 'En quinconce — chaque moto décalée dans la voie', en: 'Staggered — each motorcycle offset in the lane' },
      { fr: 'Côte à côte dans la même voie', en: 'Side by side in the same lane' },
      { fr: 'Chacun dans une voie différente', en: 'Each in a different lane' },
    ],
    correctIndex: 1,
    explanationFr: 'La formation en quinconce donne à chaque motocycliste son propre espace de sécurité. Le premier roule à gauche, le deuxième à droite, et ainsi de suite.',
    explanationEn: 'The staggered formation gives each rider their own safety space. The first rider takes the left, the second takes the right, and so on.',
  },
  {
    id: 'qc-47',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous voyez une tache sombre et brillante sur la chaussée à une intersection. Qu\'est-ce probablement ?',
    questionEn: 'You see a dark shiny patch on the road at an intersection. What is it probably?',
    options: [
      { fr: 'Une flaque d\'eau propre', en: 'A clean puddle of water' },
      { fr: 'Une fuite de diesel ou d\'huile, très glissante', en: 'A diesel or oil leak, very slippery' },
      { fr: 'Une marque de freinage inoffensive', en: 'A harmless skid mark' },
      { fr: 'De l\'asphalte fraîchement posé', en: 'Freshly laid asphalt' },
    ],
    correctIndex: 1,
    explanationFr: 'Les taches sombres et brillantes aux intersections sont souvent du diesel ou de l\'huile — extrêmement glissants. Évitez-les. Si impossible, traversez en ligne droite sans freiner.',
    explanationEn: 'Dark shiny patches at intersections are often diesel or oil — extremely slippery. Avoid them. If unavoidable, cross in a straight line without braking.',
  },
  {
    id: 'qc-48',
    province: 'qc',
    category: 'skills',
    questionFr: 'Vous entrez sur une autoroute par une bretelle d\'accès. Comment vous insérez-vous ?',
    questionEn: 'You are entering a highway via an on-ramp. How do you merge into traffic?',
    options: [
      { fr: 'Vous arrêter au bout de la bretelle et attendre un espace', en: 'Stop at the end of the ramp and wait for a gap' },
      { fr: 'Accélérer à la vitesse de l\'autoroute et trouver un espace libre', en: 'Accelerate to highway speed and find an open gap' },
      { fr: 'Klaxonner pour signaler votre présence', en: 'Honk to signal your presence' },
      { fr: 'Forcer l\'insertion car vous avez priorité', en: 'Force your way in because you have priority' },
    ],
    correctIndex: 1,
    explanationFr: 'Utilisez la bretelle pour atteindre la vitesse de l\'autoroute. Vérifiez vos angles morts. Trouvez un espace et insérez-vous sans forcer. N\'arrêtez jamais au bout de la bretelle.',
    explanationEn: 'Use the ramp to reach highway speed. Check your blind spots. Find a gap and merge without forcing. Never stop at the end of the ramp.',
  },
  {
    id: 'qc-49',
    province: 'qc',
    category: 'skills',
    questionFr: 'La nuit, en zone non éclairée, un animal surgit devant vous. Que faites-vous ?',
    questionEn: 'At night in an unlit area, an animal suddenly appears in front of you. What do you do?',
    options: [
      { fr: 'Virer brusquement pour l\'éviter', en: 'Swerve sharply to avoid it' },
      { fr: 'Freiner progressivement des deux freins et viser un côté si possible', en: 'Brake progressively with both brakes and aim to one side if possible' },
      { fr: 'Accélérer pour le dépasser avant qu\'il bouge', en: 'Accelerate to pass before it moves' },
      { fr: 'Couper les phares pour ne pas effrayer l\'animal', en: 'Turn off headlights so you do not startle the animal' },
    ],
    correctIndex: 1,
    explanationFr: 'Freinez progressivement. Évitez les virages brusques qui peuvent vous faire chuter. Si possible, visez le côté déjà passé par l\'animal. Les manœuvres brusques causent plus d\'accidents.',
    explanationEn: 'Brake progressively. Avoid sharp swerves that can cause a fall. If possible, aim for the side the animal has already passed. Sudden maneuvers cause more accidents.',
  },
  {
    id: 'qc-50',
    province: 'qc',
    category: 'skills',
    questionFr: 'Il vient de pleuvoir et vous roulez sur des lignes de marquage peintes. Que devez-vous savoir ?',
    questionEn: 'It just rained and you are riding over painted road markings. What should you know?',
    options: [
      { fr: 'Les lignes peintes sont plus glissantes que l\'asphalte mouillé', en: 'Painted markings are more slippery than wet asphalt' },
      { fr: 'Les lignes peintes sont aussi sécuritaires par temps mouillé', en: 'Painted markings are just as safe in wet conditions' },
      { fr: 'La pluie rend les lignes plus adhérentes', en: 'Rain makes painted lines grippier' },
      { fr: 'Seulement les lignes jaunes sont glissantes', en: 'Only yellow lines are slippery' },
    ],
    correctIndex: 0,
    explanationFr: 'Les lignes peintes sont très glissantes quand elles sont mouillées. Évitez de freiner ou d\'accélérer dessus. Traversez-les en ligne droite sans manœuvres brusques.',
    explanationEn: 'Painted lines are very slippery when wet. Avoid braking or accelerating on them. Cross them in a straight line without sudden maneuvers.',
  },

  // ============================
  // ONTARIO (MTO) — 6 questions
  // ============================
  {
    id: 'on-01',
    province: 'on',
    category: 'licensing',
    questionFr: 'Quelle est la première étape pour obtenir un permis moto en Ontario ?',
    questionEn: 'What is the first step to getting a motorcycle license in Ontario?',
    options: [
      { fr: 'Obtenir un permis M', en: 'Get an M license' },
      { fr: 'Obtenir un permis M1', en: 'Get an M1 license' },
      { fr: 'Réussir un cours de conduite', en: 'Pass a driving course' },
      { fr: 'Réussir le test routier', en: 'Pass the road test' },
    ],
    correctIndex: 1,
    explanationFr: 'En Ontario, la première étape est d\'obtenir le permis M1 en réussissant un examen écrit au bureau du MTO.',
    explanationEn: 'In Ontario, the first step is to get an M1 license by passing a written exam at an MTO office.',
  },
  {
    id: 'on-02',
    province: 'on',
    category: 'licensing',
    questionFr: 'Combien de temps est valide le permis M1 en Ontario ?',
    questionEn: 'How long is an Ontario M1 license valid for?',
    options: [
      { fr: '30 jours', en: '30 days' },
      { fr: '60 jours', en: '60 days' },
      { fr: '90 jours', en: '90 days' },
      { fr: '5 ans', en: '5 years' },
    ],
    correctIndex: 2,
    explanationFr: 'Le permis M1 est valide 90 jours. Durant cette période, vous pouvez pratiquer avec des restrictions comme ne pas conduire la nuit ou sur les autoroutes.',
    explanationEn: 'The M1 license is valid for 90 days. During this period, you can practice with restrictions such as no night riding or highway riding.',
  },
  {
    id: 'on-03',
    province: 'on',
    category: 'rules',
    questionFr: 'Avec un permis M1 en Ontario, est-il permis de circuler la nuit ?',
    questionEn: 'With an M1 license in Ontario, is it permitted to ride at night?',
    options: [
      { fr: 'Oui, sans restriction', en: 'Yes, without restriction' },
      { fr: 'Non, la conduite de nuit est interdite', en: 'No, night riding is prohibited' },
      { fr: 'Oui, mais seulement sur les routes secondaires', en: 'Yes, but only on secondary roads' },
      { fr: 'Oui, avec un accompagnateur expérimenté', en: 'Yes, with an experienced companion' },
    ],
    correctIndex: 1,
    explanationFr: 'Avec le permis M1, la conduite de nuit est interdite. Vous devez également éviter les autoroutes et les voies rapides.',
    explanationEn: 'With an M1 license, night riding is prohibited. You must also avoid expressways and freeways.',
  },
  {
    id: 'on-04',
    province: 'on',
    category: 'safety',
    questionFr: 'Quel équipement est obligatoire pour les conducteurs de moto en Ontario ?',
    questionEn: 'What equipment is mandatory for motorcycle riders in Ontario?',
    options: [
      { fr: 'Casque approuvé et gants', en: 'Approved helmet and gloves' },
      { fr: 'Casque approuvé uniquement', en: 'Approved helmet only' },
      { fr: 'Casque approuvé et veste de protection', en: 'Approved helmet and protective jacket' },
      { fr: 'Aucun équipement obligatoire', en: 'No equipment mandatory' },
    ],
    correctIndex: 1,
    explanationFr: 'En Ontario, seul le port d\'un casque approuvé est obligatoire par la loi. Les autres équipements (gants, veste) sont fortement recommandés.',
    explanationEn: 'In Ontario, only wearing an approved helmet is mandatory by law. Other gear (gloves, jacket) is strongly recommended.',
  },
  {
    id: 'on-05',
    province: 'on',
    category: 'licensing',
    questionFr: 'Après combien de temps peut-on passer de M1 à M2 en Ontario ?',
    questionEn: 'After how long can you move from M1 to M2 in Ontario?',
    options: [
      { fr: '30 jours', en: '30 days' },
      { fr: '60 jours', en: '60 days' },
      { fr: 'Immédiatement après un cours MORES', en: 'Immediately after a MORES course' },
      { fr: '90 jours ou après un cours approuvé', en: '90 days or after an approved course' },
    ],
    correctIndex: 3,
    explanationFr: 'On peut passer au M2 après 90 jours avec M1, ou immédiatement en complétant un cours de motocyclisme approuvé par le MTO.',
    explanationEn: 'You can move to M2 after 90 days with M1, or immediately by completing an MTO-approved motorcycle safety course.',
  },
  {
    id: 'on-06',
    province: 'on',
    category: 'rules',
    questionFr: 'En Ontario, un motocycliste peut-il transporter un passager avec un permis M2 ?',
    questionEn: 'In Ontario, can a motorcyclist carry a passenger with an M2 license?',
    options: [
      { fr: 'Oui, sans restriction', en: 'Yes, without restriction' },
      { fr: 'Non, c\'est interdit', en: 'No, it is prohibited' },
      { fr: 'Oui, après 6 mois de M2', en: 'Yes, after 6 months of M2' },
      { fr: 'Oui, mais seulement sur des routes locales', en: 'Yes, but only on local roads' },
    ],
    correctIndex: 0,
    explanationFr: 'Avec le permis M2, vous pouvez transporter des passagers. Les restrictions principales sont : alcool 0,00% et certaines restrictions de nuit.',
    explanationEn: 'With an M2 license, you can carry passengers. Main restrictions are: 0.00% alcohol and some nighttime restrictions.',
  },
];

// Gear checklist items
export interface GearItem {
  id: string;
  critical: boolean;
  nameFr: string;
  nameEn: string;
  descFr: string;
  descEn: string;
  icon: string;
}

export const gearItems: GearItem[] = [
  {
    id: 'helmet',
    critical: true,
    nameFr: 'Casque intégral homologué',
    nameEn: 'Approved Full-Face Helmet',
    descFr: 'Obligatoire par la loi. Le casque intégral protège la tête et le menton. Recherchez les certifications DOT, ECE 22.06 ou SNELL.',
    descEn: 'Mandatory by law. A full-face helmet protects the head and chin. Look for DOT, ECE 22.06 or SNELL certifications.',
    icon: '🪖',
  },
  {
    id: 'jacket',
    critical: true,
    nameFr: 'Veste de moto avec armures',
    nameEn: 'Motorcycle Jacket with Armor',
    descFr: 'Cuir ou textile avec armures aux épaules, coudes et dos. Protège contre l\'abrasion et les chocs en cas de chute.',
    descEn: 'Leather or textile with armor at shoulders, elbows and back. Protects against abrasion and impact in a fall.',
    icon: '🧥',
  },
  {
    id: 'gloves',
    critical: true,
    nameFr: 'Gants de moto',
    nameEn: 'Motorcycle Gloves',
    descFr: 'Les mains sont la première chose qu\'on tend lors d\'une chute. Gants avec armures aux paumes et articulations.',
    descEn: 'Hands are the first thing we extend in a fall. Gloves with palm and knuckle armor.',
    icon: '🧤',
  },
  {
    id: 'boots',
    critical: true,
    nameFr: 'Bottes de moto',
    nameEn: 'Motorcycle Boots',
    descFr: 'Protègent les chevilles et les pieds. Semelle antidérapante, renforts aux malléoles, fermeture sécurisée.',
    descEn: 'Protect ankles and feet. Non-slip sole, ankle reinforcements, secure closure.',
    icon: '👢',
  },
  {
    id: 'pants',
    critical: false,
    nameFr: 'Pantalon de moto avec armures',
    nameEn: 'Motorcycle Pants with Armor',
    descFr: 'Armures aux genoux et hanches. Cuir ou textile renforcé. Fortement recommandé pour protéger le bas du corps.',
    descEn: 'Knee and hip armor. Leather or reinforced textile. Highly recommended to protect the lower body.',
    icon: '👖',
  },
  {
    id: 'eyewear',
    critical: false,
    nameFr: 'Protection oculaire (lunettes/visière)',
    nameEn: 'Eye Protection (goggles/visor)',
    descFr: 'Requis si le casque est ouvert. Protège contre le vent, les insectes, les débris. Visière anti-UV recommandée.',
    descEn: 'Required if helmet is open-face. Protects against wind, insects, debris. Anti-UV visor recommended.',
    icon: '🥽',
  },
  {
    id: 'hiviz',
    critical: false,
    nameFr: 'Gilet ou vêtements haute visibilité',
    nameEn: 'High-Visibility Vest or Clothing',
    descFr: 'Améliore considérablement votre visibilité pour les autres conducteurs, surtout la nuit ou par mauvais temps.',
    descEn: 'Significantly improves your visibility to other drivers, especially at night or in bad weather.',
    icon: '🦺',
  },
  {
    id: 'earplugs',
    critical: false,
    nameFr: 'Bouchons d\'oreilles',
    nameEn: 'Ear Plugs',
    descFr: 'Le bruit du vent à haute vitesse peut causer des dommages auditifs permanents. Les bouchons réduisent la fatigue.',
    descEn: 'Wind noise at high speed can cause permanent hearing damage. Ear plugs reduce fatigue.',
    icon: '🔇',
  },
];

// Licensing steps by province
export interface LicensingStep {
  id: string;
  province: Province;
  stepNumber: number;
  titleFr: string;
  titleEn: string;
  descFr: string;
  descEn: string;
}

export const licensingSteps: LicensingStep[] = [
  // Quebec steps
  {
    id: 'qc-step-1',
    province: 'qc',
    stepNumber: 1,
    titleFr: 'Réussir l\'examen théorique SAAQ',
    titleEn: 'Pass the SAAQ Theory Exam',
    descFr: 'Rendez-vous dans un point de service SAAQ. Étudiez le guide "Conduire une moto". Réussissez l\'examen de connaissance pour obtenir le permis apprenti conducteur de classe 6.',
    descEn: 'Visit a SAAQ service point. Study the "Operating a Motorcycle" guide. Pass the knowledge test to get the Class 6 learner\'s license.',
  },
  {
    id: 'qc-step-2',
    province: 'qc',
    stepNumber: 2,
    titleFr: 'Compléter un cours de conduite reconnu',
    titleEn: 'Complete an Approved Riding Course',
    descFr: 'Suivez un cours de conduite moto dans une école reconnue par la SAAQ (ex: Tecnic). Cela inclut la théorie, les manœuvres en espace fermé et la conduite sur route.',
    descEn: 'Complete a motorcycle course at a SAAQ-recognized school (e.g., Tecnic). This includes theory, closed-space maneuvers and road riding.',
  },
  {
    id: 'qc-step-3',
    province: 'qc',
    stepNumber: 3,
    titleFr: 'Période d\'apprentissage de 12 mois',
    titleEn: '12-Month Learning Period',
    descFr: 'Conduisez avec votre permis probatoire pendant au moins 12 mois. Respectez les restrictions : taux d\'alcool 0,00%, pas de passager les 6 premiers mois.',
    descEn: 'Ride with your probationary license for at least 12 months. Follow restrictions: 0.00% blood alcohol, no passenger for the first 6 months.',
  },
  {
    id: 'qc-step-4',
    province: 'qc',
    stepNumber: 4,
    titleFr: 'Examen de conduite sur route',
    titleEn: 'On-Road Driving Exam',
    descFr: 'Après 12 mois, prenez rendez-vous pour l\'examen de conduite sur route avec un examinateur SAAQ. Pratiquez les manœuvres d\'urgence et les virages.',
    descEn: 'After 12 months, schedule your on-road exam with a SAAQ examiner. Practice emergency maneuvers and cornering.',
  },
  {
    id: 'qc-step-5',
    province: 'qc',
    stepNumber: 5,
    titleFr: 'Obtenir le permis de classe 6 régulier',
    titleEn: 'Get Your Regular Class 6 License',
    descFr: 'Après avoir réussi l\'examen de conduite, vous obtenez le permis de classe 6 régulier. Bienvenue dans le monde des motocyclistes !',
    descEn: 'After passing the road test, you receive your regular Class 6 license. Welcome to the world of motorcyclists!',
  },
  // Ontario steps
  {
    id: 'on-step-1',
    province: 'on',
    stepNumber: 1,
    titleFr: 'Réussir le test écrit M1 au MTO',
    titleEn: 'Pass the M1 Written Test at MTO',
    descFr: 'Rendez-vous dans un centre DriveTest. Étudiez le Manuel du motocycliste de l\'Ontario. Réussissez l\'examen de vision et le test écrit pour obtenir le M1.',
    descEn: 'Visit a DriveTest centre. Study the Ontario Motorcycle Handbook. Pass the vision exam and written test to get your M1.',
  },
  {
    id: 'on-step-2',
    province: 'on',
    stepNumber: 2,
    titleFr: 'Pratiquer avec le permis M1 (90 jours)',
    titleEn: 'Practice with M1 License (90 Days)',
    descFr: 'Avec le M1, pratiquez pendant au moins 60 jours. Restrictions : pas de nuit, pas d\'autoroute, alcool 0,00%. Idéalement, suivez un cours de sécurité approuvé.',
    descEn: 'With M1, practice for at least 60 days. Restrictions: no night riding, no expressways, 0.00% alcohol. Ideally, take an approved safety course.',
  },
  {
    id: 'on-step-3',
    province: 'on',
    stepNumber: 3,
    titleFr: 'Passer le test M2 (conduite sur route)',
    titleEn: 'Take the M2 Road Test',
    descFr: 'Après 60 jours de M1, prenez rendez-vous pour le test M2. Les compétences testées incluent : démarrage, arrêts, virages, changements de voie, distance de suivi.',
    descEn: 'After 60 days of M1, schedule your M2 road test. Skills tested: starting, stopping, turning, lane changes, following distance.',
  },
  {
    id: 'on-step-4',
    province: 'on',
    stepNumber: 4,
    titleFr: 'Période M2 — 22 mois minimum',
    titleEn: 'M2 Period — Minimum 22 Months',
    descFr: 'Conduisez avec le M2 pendant au moins 22 mois (ou 12 mois si vous avez suivi un cours approuvé). Alcool 0,00% requis.',
    descEn: 'Ride with M2 for at least 22 months (or 12 months if you completed an approved course). 0.00% alcohol required.',
  },
  {
    id: 'on-step-5',
    province: 'on',
    stepNumber: 5,
    titleFr: 'Passer le test final M — Permis complet',
    titleEn: 'Pass the Final M Test — Full License',
    descFr: 'Le test M final est plus exigeant : il inclut des manœuvres d\'urgence, freinage d\'urgence, et conduite sur route à vitesse normale. Réussissez pour obtenir le M complet.',
    descEn: 'The final M test is more demanding: it includes emergency maneuvers, emergency braking, and road riding at normal speeds. Pass to get your full M license.',
  },
];
