// exam-data.ts — Original quiz questions for QC (SAAQ) and ON (MTO)
// Questions are ORIGINAL, inspired by official handbooks — NOT copied.
// Sources: SAAQ "Conduire une moto", MTO "Motorcycle Handbook"
// Disclaimer: Not affiliated with SAAQ or MTO. Educational purposes only.

export type Province = 'qc' | 'on';
export type Category =
  | 'Road Rules'
  | 'Road Signs'
  | 'Motorcycle Safety'
  | 'Quebec Law'
  | 'Riding Scenarios';

export interface Question {
  id: number;
  province: Province;
  category: Category;
  q: string;          // French question (max 20 words per sentence)
  qEN: string;        // English question (max 20 words per sentence)
  options: string[];  // 4 French answer options
  optionsEN: string[]; // 4 English answer options
  answer: number;     // correct option index (0–3)
  explanation: string; // "FR explanation / EN explanation"
}

export const questions: Question[] = [

  // ============================================================
  // ROAD RULES / Règles de la route — questions 1–10
  // ============================================================

  {
    id: 1,
    province: 'qc',
    category: 'Road Rules',
    q: 'Quelle distance minimale en secondes devez-vous maintenir derrière un véhicule ?',
    qEN: 'What minimum following distance in seconds must you keep behind a vehicle?',
    options: ['1 seconde', '2 secondes', '3 secondes', '5 secondes'],
    optionsEN: ['1 second', '2 seconds', '3 seconds', '5 seconds'],
    answer: 2,
    explanation: 'En moto, maintenez au moins 3 secondes. Choisissez un repère fixe. Comptez 3 secondes après que le véhicule devant le dépasse. En pluie, doublez la distance. / On a motorcycle, keep at least 3 seconds. Pick a fixed marker. Count 3 seconds after the vehicle ahead passes it. In rain, double this distance.',
  },
  {
    id: 2,
    province: 'qc',
    category: 'Road Rules',
    q: 'Quelle est la limite de vitesse sur une autoroute au Québec ?',
    qEN: 'What is the speed limit on a Quebec highway?',
    options: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
    optionsEN: ['90 km/h', '100 km/h', '110 km/h', '120 km/h'],
    answer: 1,
    explanation: 'La limite sur les autoroutes québécoises est 100 km/h. Sur les routes secondaires, elle est généralement 90 km/h. En ville sans panneau, c\'est 50 km/h. / Highway speed limit in Quebec is 100 km/h. Secondary roads are usually 90 km/h. In urban areas without a sign, it\'s 50 km/h.',
  },
  {
    id: 3,
    province: 'qc',
    category: 'Road Rules',
    q: 'Dans une zone scolaire active, quelle vitesse maximale devez-vous respecter ?',
    qEN: 'In an active school zone, what is the maximum speed allowed?',
    options: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'],
    optionsEN: ['20 km/h', '30 km/h', '40 km/h', '50 km/h'],
    answer: 1,
    explanation: 'Les zones scolaires actives affichent des panneaux fluorescents jaune-vert. La limite est 30 km/h quand des enfants sont présents. Les amendes sont plus élevées dans ces zones. / Active school zones show fluorescent yellow-green signs. The limit is 30 km/h when children are present. Fines are higher in these zones.',
  },
  {
    id: 4,
    province: 'qc',
    category: 'Road Rules',
    q: 'Dans une zone de chantier, que se passe-t-il si vous dépassez la limite affichée ?',
    qEN: 'In a construction zone, what happens if you exceed the posted speed limit?',
    options: [
      'Les amendes sont normales',
      'Les amendes sont doublées',
      'Votre permis est suspendu immédiatement',
      'Rien de spécial',
    ],
    optionsEN: [
      'Fines are normal',
      'Fines are doubled',
      'Your license is immediately suspended',
      'Nothing special',
    ],
    answer: 1,
    explanation: 'Dans les zones de chantier au Québec, les amendes pour excès de vitesse sont doublées. Respectez la limite affichée sur les panneaux oranges, même la nuit. / In Quebec construction zones, speeding fines are doubled. Follow the speed limit shown on orange signs, even at night.',
  },
  {
    id: 5,
    province: 'qc',
    category: 'Road Rules',
    q: 'À un carrefour non contrôlé, qui a la priorité de passage ?',
    qEN: 'At an uncontrolled intersection, who has the right of way?',
    options: [
      'Le plus rapide',
      'Celui qui arrive en premier',
      'Le véhicule venant de droite',
      'Le véhicule le plus grand',
    ],
    optionsEN: [
      'The fastest driver',
      'The first to arrive',
      'The vehicle coming from the right',
      'The largest vehicle',
    ],
    answer: 2,
    explanation: 'À un carrefour sans panneaux, cédez le passage au véhicule venant de votre droite. Si vous arrivez en même temps, attendez et regardez toujours à droite. / At an intersection with no signs, yield to the vehicle on your right. If you arrive simultaneously, wait and always check to your right.',
  },
  {
    id: 6,
    province: 'qc',
    category: 'Road Rules',
    q: 'Où devez-vous immobiliser votre moto lorsque vous voyez un panneau d\'arrêt ?',
    qEN: 'Where must you stop your motorcycle when you see a stop sign?',
    options: [
      'Avant la ligne d\'arrêt blanche',
      'Sur la ligne d\'arrêt',
      'Après la ligne d\'arrêt',
      'N\'importe où avant le carrefour',
    ],
    optionsEN: [
      'Before the white stop line',
      'On the stop line',
      'After the stop line',
      'Anywhere before the intersection',
    ],
    answer: 0,
    explanation: 'Vous devez vous arrêter avant la ligne d\'arrêt blanche peinte sur la route. Si elle est absente, arrêtez avant le trottoir ou le bord de la chaussée. / You must stop before the white stop line painted on the road. If absent, stop before the curb or the edge of the roadway.',
  },
  {
    id: 7,
    province: 'qc',
    category: 'Road Rules',
    q: 'En ville, sans panneau affiché, quelle est la limite de vitesse par défaut ?',
    qEN: 'In a city with no posted sign, what is the default speed limit?',
    options: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'],
    optionsEN: ['30 km/h', '40 km/h', '50 km/h', '60 km/h'],
    answer: 2,
    explanation: 'En milieu urbain sans panneau, la limite de vitesse par défaut est 50 km/h au Québec. Restez vigilant, des zones à 30 km/h existent aussi. / In urban areas without a sign, the default speed limit is 50 km/h in Quebec. Stay alert, as 30 km/h zones also exist.',
  },
  {
    id: 8,
    province: 'qc',
    category: 'Road Rules',
    q: 'Vous approchez d\'un feu jaune à vitesse normale. Que devez-vous faire ?',
    qEN: 'You approach a yellow light at normal speed. What should you do?',
    options: [
      'Accélérer pour passer avant le rouge',
      'Ralentir et vous arrêter si c\'est sécuritaire',
      'Continuer à la même vitesse',
      'Klaxonner et passer',
    ],
    optionsEN: [
      'Speed up to pass before red',
      'Slow down and stop if it is safe',
      'Continue at the same speed',
      'Honk and proceed',
    ],
    answer: 1,
    explanation: 'Un feu jaune signifie que le rouge arrive bientôt. Vous devez ralentir et vous arrêter si c\'est sécuritaire. N\'accélérez jamais pour passer un feu jaune. / A yellow light means red is coming. You must slow down and stop if it is safe. Never speed up to beat a yellow light.',
  },
  {
    id: 9,
    province: 'qc',
    category: 'Road Rules',
    q: 'Sur une route à voie unique, pouvez-vous dépasser par la droite ?',
    qEN: 'On a single-lane road, can you pass a vehicle on the right?',
    options: [
      'Oui, toujours permis',
      'Non, jamais permis',
      'Oui, seulement si le conducteur tourne à gauche',
      'Oui, sur les accotements pavés',
    ],
    optionsEN: [
      'Yes, always allowed',
      'No, never allowed',
      'Yes, only if the driver is turning left',
      'Yes, on paved shoulders',
    ],
    answer: 2,
    explanation: 'On ne dépasse par la droite que si le véhicule devant tourne à gauche. Dépasser sur l\'accotement est illégal et dangereux. Sur autoroute, gardez la droite. / You may pass on the right only if the vehicle ahead is turning left. Passing on the shoulder is illegal and dangerous. On highways, keep right.',
  },
  {
    id: 10,
    province: 'qc',
    category: 'Road Rules',
    q: 'Sur une route à plusieurs voies dans le même sens, quelle voie utilisez-vous normalement ?',
    qEN: 'On a multi-lane road going one direction, which lane do you normally use?',
    options: [
      'La voie de gauche pour être visible',
      'La voie de droite, sauf pour dépasser',
      'N\'importe quelle voie',
      'La voie du centre',
    ],
    optionsEN: [
      'The left lane to be more visible',
      'The right lane, except to pass',
      'Any lane you prefer',
      'The center lane',
    ],
    answer: 1,
    explanation: 'Roulez dans la voie de droite et utilisez la gauche seulement pour dépasser. Une fois le dépassement terminé, revenez à droite. La voie de gauche est réservée au dépassement. / Drive in the right lane and use the left only to pass. Once passing is complete, return to the right. The left lane is for passing only.',
  },

  // ============================================================
  // ROAD SIGNS / Signalisation routière — questions 11–20
  // ============================================================

  {
    id: 11,
    province: 'qc',
    category: 'Road Signs',
    q: 'Quel panneau de signalisation est toujours octogonal et rouge ?',
    qEN: 'Which road sign is always octagonal and red?',
    options: [
      'Le panneau de cédez le passage',
      'Le panneau d\'arrêt',
      'Le panneau de sens interdit',
      'Le panneau de danger',
    ],
    optionsEN: [
      'The yield sign',
      'The stop sign',
      'The no-entry sign',
      'The danger sign',
    ],
    answer: 1,
    explanation: 'Le panneau d\'arrêt est le seul panneau octogonal rouge. Sa forme unique vous permet de le reconnaître même s\'il est partiellement caché par la neige. / The stop sign is the only octagonal red sign. Its unique shape lets you recognize it even when partially covered by snow.',
  },
  {
    id: 12,
    province: 'qc',
    category: 'Road Signs',
    q: 'Un triangle rouge pointé vers le bas signifie quoi sur la route ?',
    qEN: 'What does a downward-pointing red triangle mean on the road?',
    options: [
      'Arrêtez complètement',
      'Cédez le passage',
      'Danger à l\'avant',
      'Route barrée',
    ],
    optionsEN: [
      'Stop completely',
      'Yield the right of way',
      'Danger ahead',
      'Road closed',
    ],
    answer: 1,
    explanation: 'Le triangle inversé rouge et blanc est le panneau de cédez le passage. Vous devez ralentir et laisser passer les autres usagers avant d\'avancer. / The inverted red and white triangle is the yield sign. You must slow down and let other users pass before proceeding.',
  },
  {
    id: 13,
    province: 'qc',
    category: 'Road Signs',
    q: 'De quelle couleur et forme sont les panneaux d\'avertissement au Québec ?',
    qEN: 'What color and shape are warning signs in Quebec?',
    options: [
      'Rouges et ronds',
      'Oranges et rectangulaires',
      'Jaunes en forme de diamant',
      'Verts et ovales',
    ],
    optionsEN: [
      'Red and round',
      'Orange and rectangular',
      'Yellow diamond shape',
      'Green and oval',
    ],
    answer: 2,
    explanation: 'Les panneaux d\'avertissement sont jaunes en forme de diamant. Ils vous préviennent d\'un danger à venir : courbe serrée, intersection, dos d\'âne. Réduisez votre vitesse. / Warning signs are yellow diamond shapes. They alert you to upcoming hazards: sharp curves, intersections, speed bumps. Reduce your speed.',
  },
  {
    id: 14,
    province: 'qc',
    category: 'Road Signs',
    q: 'Les panneaux oranges sur la route signalent quoi ?',
    qEN: 'What do orange signs on the road indicate?',
    options: [
      'Une zone scolaire',
      'Une zone de travaux',
      'Une zone résidentielle',
      'Une zone industrielle',
    ],
    optionsEN: [
      'A school zone',
      'A construction zone',
      'A residential zone',
      'An industrial zone',
    ],
    answer: 1,
    explanation: 'Les panneaux oranges signalent une zone de travaux. Des règles spéciales s\'appliquent : vitesse réduite et amendes doublées. Respectez-les même si aucun travailleur n\'est visible. / Orange signs indicate a construction zone. Special rules apply: reduced speed and doubled fines. Follow them even if no workers are visible.',
  },
  {
    id: 15,
    province: 'qc',
    category: 'Road Signs',
    q: 'Quel panneau vous prévient d\'un passage à niveau ferroviaire à l\'avant ?',
    qEN: 'Which sign warns you of a railway crossing ahead?',
    options: [
      'Un panneau vert rectangulaire',
      'Un panneau rond avec une croix en X',
      'Un panneau rouge octogonal',
      'Un panneau bleu carré',
    ],
    optionsEN: [
      'A green rectangular sign',
      'A round sign with an X cross',
      'A red octagonal sign',
      'A blue square sign',
    ],
    answer: 1,
    explanation: 'Le panneau de passage à niveau est rond avec une croix de Saint-André (X). Il vous avertit qu\'un chemin de fer traverse la route à l\'avant. / The railway crossing sign is round with a Saint Andrew\'s cross (X). It warns you that a railway crosses the road ahead.',
  },
  {
    id: 16,
    province: 'qc',
    category: 'Road Signs',
    q: 'Les panneaux verts rectangulaires sur les autoroutes donnent quelles informations ?',
    qEN: 'What information do green rectangular signs on highways provide?',
    options: [
      'Des avertissements de danger',
      'Des indications de direction et de distance',
      'Des limites de vitesse',
      'Des zones de travaux',
    ],
    optionsEN: [
      'Danger warnings',
      'Direction and distance information',
      'Speed limits',
      'Construction zones',
    ],
    answer: 1,
    explanation: 'Les panneaux verts sont des panneaux de direction. Ils indiquent les destinations, les distances et les sorties d\'autoroute. Ils vous guident vers votre destination. / Green signs are directional signs. They show destinations, distances, and highway exits. They guide you toward your destination.',
  },
  {
    id: 17,
    province: 'qc',
    category: 'Road Signs',
    q: 'Vous voyez un feu rouge clignotant. Que devez-vous faire ?',
    qEN: 'You see a flashing red traffic light. What must you do?',
    options: [
      'Continuer sans vous arrêter',
      'Ralentir et continuer prudemment',
      'Vous arrêter complètement, puis repartir si libre',
      'Attendre que le feu devienne vert',
    ],
    optionsEN: [
      'Continue without stopping',
      'Slow down and continue carefully',
      'Stop completely, then proceed if clear',
      'Wait for the light to turn green',
    ],
    answer: 2,
    explanation: 'Un feu rouge clignotant se traite comme un panneau d\'arrêt. Arrêtez complètement, vérifiez que l\'intersection est libre, puis repartez. / A flashing red light is treated like a stop sign. Stop completely, check that the intersection is clear, then proceed.',
  },
  {
    id: 18,
    province: 'qc',
    category: 'Road Signs',
    q: 'Un feu jaune clignotant vous indique de faire quoi ?',
    qEN: 'What does a flashing amber traffic light tell you to do?',
    options: [
      'Vous arrêter complètement',
      'Ralentir et avancer avec prudence',
      'Accélérer pour dégager l\'intersection',
      'Attendre qu\'il soit fixe',
    ],
    optionsEN: [
      'Stop completely',
      'Slow down and proceed with caution',
      'Speed up to clear the intersection',
      'Wait for it to become steady',
    ],
    answer: 1,
    explanation: 'Un feu jaune clignotant signifie : ralentissez et soyez prudent. Vous pouvez continuer, mais regardez bien dans toutes les directions avant d\'avancer. / A flashing amber light means: slow down and be careful. You may continue, but look carefully in all directions before proceeding.',
  },
  {
    id: 19,
    province: 'qc',
    category: 'Road Signs',
    q: 'Vous voyez un panneau rouge avec une barre blanche horizontale. Que signifie-t-il ?',
    qEN: 'You see a red sign with a white horizontal bar. What does it mean?',
    options: [
      'Arrêtez et attendez',
      'Entrée interdite dans cette direction',
      'Limite de vitesse réduite à zéro',
      'Zone de chantier',
    ],
    optionsEN: [
      'Stop and wait',
      'No entry in this direction',
      'Speed limit reduced to zero',
      'Construction zone',
    ],
    answer: 1,
    explanation: 'Ce panneau signifie qu\'il est interdit d\'entrer dans cette direction. On le voit souvent à la sortie d\'une autoroute ou d\'une rue à sens unique. / This sign means entry is forbidden in this direction. It\'s often seen at highway exits or one-way street entrances.',
  },
  {
    id: 20,
    province: 'qc',
    category: 'Road Signs',
    q: 'Les panneaux blancs rectangulaires indiquent généralement quoi ?',
    qEN: 'What do white rectangular signs generally indicate?',
    options: [
      'Des avertissements de danger',
      'Des règlements à respecter',
      'Des destinations à suivre',
      'Des zones de travaux',
    ],
    optionsEN: [
      'Danger warnings',
      'Regulations to follow',
      'Destinations to follow',
      'Construction zones',
    ],
    answer: 1,
    explanation: 'Les panneaux blancs rectangulaires sont des panneaux réglementaires. Ils indiquent des règles que vous devez respecter : vitesse maximale, stationnement, direction. / White rectangular signs are regulatory signs. They show rules you must follow: maximum speed, parking, direction.',
  },

  // ============================================================
  // MOTORCYCLE SAFETY & TECHNIQUE / Sécurité et technique — questions 21–30
  // ============================================================

  {
    id: 21,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Au Québec, quel équipement est obligatoire par la loi pour conduire une moto ?',
    qEN: 'In Quebec, what equipment is required by law to ride a motorcycle?',
    options: [
      'Des gants de cuir',
      'Un casque homologué',
      'Une veste de cuir',
      'Des bottes montantes',
    ],
    optionsEN: [
      'Leather gloves',
      'An approved helmet',
      'A leather jacket',
      'Ankle-high boots',
    ],
    answer: 1,
    explanation: 'La loi québécoise oblige tout motocycliste à porter un casque homologué. Il doit être certifié selon les normes reconnues. Les autres équipements sont fortement recommandés mais pas obligatoires par la loi. / Quebec law requires every motorcyclist to wear a certified helmet. It must meet recognized safety standards. Other gear is strongly recommended but not legally required.',
  },
  {
    id: 22,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Quelle distance de suivi est recommandée pour un motocycliste derrière une voiture ?',
    qEN: 'What following distance is recommended for a motorcyclist behind a car?',
    options: [
      '1 seconde',
      '2 secondes',
      '3 à 4 secondes',
      '10 secondes',
    ],
    optionsEN: [
      '1 second',
      '2 seconds',
      '3 to 4 seconds',
      '10 seconds',
    ],
    answer: 2,
    explanation: 'Un motocycliste doit maintenir 3 à 4 secondes derrière le véhicule devant. Vous êtes plus vulnérable qu\'en voiture. Plus d\'espace vous donne plus de temps pour réagir. / A motorcyclist should keep 3 to 4 seconds behind the vehicle ahead. You are more vulnerable than in a car. More space gives you more time to react.',
  },
  {
    id: 23,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Au-dessus de 25 km/h, comment amorce-t-on un virage à gauche en moto ?',
    qEN: 'Above 25 km/h, how do you initiate a left turn on a motorcycle?',
    options: [
      'Poussez le guidon droit vers l\'avant',
      'Poussez le guidon gauche vers l\'avant',
      'Tirez les deux guidons vers vous',
      'Tournez le guidon à gauche normalement',
    ],
    optionsEN: [
      'Push the right handlebar forward',
      'Push the left handlebar forward',
      'Pull both handlebars toward you',
      'Turn the handlebar left normally',
    ],
    answer: 1,
    explanation: 'En contre-braquage, poussez le guidon gauche pour aller à gauche. La moto penche à gauche et amorce le virage. C\'est contre-intuitif mais c\'est la technique correcte au-dessus de 25 km/h. / In countersteering, push the left handlebar to go left. The bike leans left and starts the turn. It feels backwards but it\'s the correct technique above 25 km/h.',
  },
  {
    id: 24,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'En freinage d\'urgence, comment utilisez-vous les freins pour arrêter le plus vite ?',
    qEN: 'In an emergency stop, how do you use brakes to stop as fast as possible?',
    options: [
      'Utilisez seulement le frein avant',
      'Utilisez seulement le frein arrière',
      'Appliquez les deux freins progressivement en même temps',
      'Coupez le moteur d\'abord',
    ],
    optionsEN: [
      'Use only the front brake',
      'Use only the rear brake',
      'Apply both brakes progressively at the same time',
      'Cut the engine first',
    ],
    answer: 2,
    explanation: 'Pour s\'arrêter le plus vite, appliquez les deux freins progressivement en même temps. Le frein avant fournit environ 70 % de la puissance de freinage. N\'écrasez pas les freins pour éviter le blocage des roues. / To stop fastest, apply both brakes progressively and simultaneously. The front brake provides about 70% of stopping power. Don\'t slam the brakes to avoid locking the wheels.',
  },
  {
    id: 25,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Dans votre voie, quelle position améliore votre visibilité et vous rend plus visible ?',
    qEN: 'In your lane, which position improves your sightlines and makes you more visible?',
    options: [
      'Le centre de la voie',
      'Le tiers gauche de la voie',
      'Le tiers droit de la voie',
      'Le bord droit de la route',
    ],
    optionsEN: [
      'The center of the lane',
      'The left third of the lane',
      'The right third of the lane',
      'The far right edge of the road',
    ],
    answer: 1,
    explanation: 'Roulez dans le tiers gauche de votre voie. Vous êtes plus visible dans les rétroviseurs des voitures devant vous. Évitez le centre car il accumule l\'huile des moteurs. / Ride in the left third of your lane. You\'re more visible in the mirrors of vehicles ahead. Avoid the center where engine oil accumulates.',
  },
  {
    id: 26,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Avant de changer de voie, que devez-vous faire en plus de vérifier vos rétroviseurs ?',
    qEN: 'Before changing lanes, what must you do in addition to checking your mirrors?',
    options: [
      'Activer le clignotant seulement',
      'Regarder par-dessus votre épaule dans l\'angle mort',
      'Accélérer légèrement',
      'Klaxonner pour avertir',
    ],
    optionsEN: [
      'Only activate the turn signal',
      'Look over your shoulder into the blind spot',
      'Accelerate slightly',
      'Honk to warn others',
    ],
    answer: 1,
    explanation: 'Les rétroviseurs ne montrent pas tout. Regardez toujours par-dessus votre épaule avant de changer de voie pour vérifier l\'angle mort. Un autre véhicule peut s\'y trouver. / Mirrors don\'t show everything. Always look over your shoulder before changing lanes to check the blind spot. Another vehicle could be hiding there.',
  },
  {
    id: 27,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'À quelle fréquence devriez-vous vérifier la pression de vos pneus de moto ?',
    qEN: 'How often should you check your motorcycle tire pressure?',
    options: [
      'Une fois par mois',
      'Une fois par semaine',
      'Avant chaque sortie',
      'Seulement après une crevaison',
    ],
    optionsEN: [
      'Once a month',
      'Once a week',
      'Before every ride',
      'Only after a flat tire',
    ],
    answer: 2,
    explanation: 'Vérifiez la pression des pneus avant chaque sortie, quand les pneus sont froids. Une pression incorrecte affecte la tenue de route et augmente le risque d\'accident. / Check tire pressure before every ride, when tires are cold. Incorrect pressure affects handling and increases the risk of an accident.',
  },
  {
    id: 28,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Par temps de pluie, comment adaptez-vous votre conduite en moto ?',
    qEN: 'In rainy weather, how do you adapt your motorcycle riding?',
    options: [
      'Accélérez pour traverser les flaques rapidement',
      'Augmentez la distance de suivi et réduisez la vitesse',
      'Utilisez seulement le frein arrière',
      'Évitez de freiner complètement',
    ],
    optionsEN: [
      'Speed up to get through puddles quickly',
      'Increase following distance and reduce speed',
      'Use only the rear brake',
      'Avoid braking completely',
    ],
    answer: 1,
    explanation: 'Sur route mouillée, doublez votre distance de suivi et réduisez votre vitesse. Le freinage prend deux fois plus de distance. Évitez les marquages au sol et les taches d\'huile. / On wet roads, double your following distance and reduce your speed. Braking takes twice as long. Avoid road markings and oil spots, which are very slippery.',
  },
  {
    id: 29,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Comment se positionnent les motocyclistes en groupe lors d\'un long trajet ?',
    qEN: 'How do motorcyclists position themselves in a group on a long ride?',
    options: [
      'En ligne droite, l\'un derrière l\'autre',
      'En formation en quinconce (décalée)',
      'Côte à côte dans la même voie',
      'Au hasard, sans formation précise',
    ],
    optionsEN: [
      'In a straight line, one behind the other',
      'In a staggered formation',
      'Side by side in the same lane',
      'Randomly, without a specific formation',
    ],
    answer: 1,
    explanation: 'La formation en quinconce est recommandée. Le premier roule à gauche, le deuxième à droite, le troisième à gauche. Chacun maintient sa propre distance de suivi. / Staggered formation is recommended. First rider on the left, second on the right, third on the left. Each rider maintains their own following distance.',
  },
  {
    id: 30,
    province: 'qc',
    category: 'Motorcycle Safety',
    q: 'Vous bâillez souvent et perdez votre concentration en roulant. Que faites-vous ?',
    qEN: 'You are yawning frequently and losing focus while riding. What do you do?',
    options: [
      'Ouvrez la visière pour l\'air frais et continuez',
      'Arrêtez-vous et reposez-vous avant de continuer',
      'Buvez un café et accélérez pour garder l\'attention',
      'Mettez de la musique forte dans vos écouteurs',
    ],
    optionsEN: [
      'Open your visor for fresh air and continue',
      'Stop and rest before continuing',
      'Drink coffee and speed up to stay alert',
      'Listen to loud music in your earbuds',
    ],
    answer: 1,
    explanation: 'La fatigue est mortelle en moto. Arrêtez-vous dès que vous sentez de la fatigue. Reposez-vous 15 à 20 minutes minimum. Continuer fatigué peut vous coûter la vie. / Fatigue is deadly on a motorcycle. Stop as soon as you feel tired. Rest for at least 15 to 20 minutes. Continuing while fatigued can cost you your life.',
  },

  // ============================================================
  // QUEBEC LAW & SAAQ SPECIFIC / Loi québécoise et SAAQ — questions 31–40
  // ============================================================

  {
    id: 31,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Quel est le taux d\'alcool autorisé pour un conducteur avec un permis d\'apprenti ?',
    qEN: 'What is the legal blood alcohol level for a learner driver in Quebec?',
    options: ['0,08 %', '0,05 %', '0,00 %', '0,10 %'],
    optionsEN: ['0.08%', '0.05%', '0.00%', '0.10%'],
    answer: 2,
    explanation: 'Un conducteur avec un permis d\'apprenti doit avoir un taux d\'alcoolémie de zéro. Cette règle s\'applique aussi aux conducteurs de moins de 22 ans et aux récidivistes. / A learner driver must have zero blood alcohol. This rule also applies to drivers under 22 and repeat offenders.',
  },
  {
    id: 32,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Avez-vous le droit de tenir et d\'utiliser votre téléphone pendant que vous conduisez ?',
    qEN: 'Can you hold and use your phone while riding your motorcycle in Quebec?',
    options: [
      'Oui, aux feux rouges seulement',
      'Oui, à basse vitesse',
      'Non, jamais en tenant le téléphone',
      'Oui, avec des écouteurs',
    ],
    optionsEN: [
      'Yes, at red lights only',
      'Yes, at low speed',
      'No, never while holding the phone',
      'Yes, with earbuds',
    ],
    answer: 2,
    explanation: 'Il est interdit de tenir et d\'utiliser un téléphone au Québec en conduisant. Arrêtez dans un endroit sécuritaire avant d\'utiliser votre téléphone. L\'amende est de 300 à 600 dollars. / Holding and using a phone while driving is prohibited in Quebec. Stop in a safe location first. The fine ranges from $300 to $600.',
  },
  {
    id: 33,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Avec un permis d\'apprenti motocycliste de classe 6R, pouvez-vous conduire seul la nuit ?',
    qEN: 'With a Class 6R learner permit, can you ride alone at night?',
    options: [
      'Oui, sans restriction',
      'Oui, jusqu\'à minuit seulement',
      'Non, vous devez être accompagné',
      'Oui, sur les routes locales',
    ],
    optionsEN: [
      'Yes, without restriction',
      'Yes, until midnight only',
      'No, you must be accompanied',
      'Yes, on local roads only',
    ],
    answer: 2,
    explanation: 'Le permis d\'apprenti 6R oblige à être accompagné d\'un titulaire de classe 6A ou 5A. La conduite de nuit est interdite et l\'alcool doit être à zéro. / The Class 6R learner permit requires being accompanied by a Class 6A or 5A license holder. Night riding is prohibited and blood alcohol must be zero.',
  },
  {
    id: 34,
    province: 'qc',
    category: 'Quebec Law',
    q: 'À combien de points d\'inaptitude votre permis peut-il être suspendu au Québec ?',
    qEN: 'At how many demerit points can your regular license be suspended in Quebec?',
    options: ['6 points', '9 points', '12 points', '15 points'],
    optionsEN: ['6 points', '9 points', '12 points', '15 points'],
    answer: 3,
    explanation: 'Au Québec, votre permis régulier peut être suspendu à 15 points d\'inaptitude sur 2 ans. Pour les apprentis, la limite est de seulement 4 points. / In Quebec, your regular license may be suspended at 15 demerit points over 2 years. For learners, the limit is only 4 points.',
  },
  {
    id: 35,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Combien de points d\'inaptitude perdez-vous pour un excès de vitesse de 21 à 30 km/h ?',
    qEN: 'How many demerit points for speeding 21 to 30 km/h over the limit?',
    options: ['1 point', '2 points', '3 points', '5 points'],
    optionsEN: ['1 point', '2 points', '3 points', '5 points'],
    answer: 2,
    explanation: 'Un excès de vitesse de 21 à 30 km/h coûte 3 points d\'inaptitude. Pour un excès de plus de 45 km/h, on perd 9 points et on risque une suspension immédiate. / Speeding 21 to 30 km/h over costs 3 demerit points. More than 45 km/h over loses 9 points and risks an immediate suspension.',
  },
  {
    id: 36,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Quel est le taux d\'alcool légal maximum pour un titulaire d\'un permis régulier ?',
    qEN: 'What is the maximum legal blood alcohol for a regular license holder in Quebec?',
    options: ['0,05 %', '0,08 %', '0,10 %', '0,06 %'],
    optionsEN: ['0.05%', '0.08%', '0.10%', '0.06%'],
    answer: 1,
    explanation: 'La limite légale d\'alcool au Québec est de 0,08 %. Entre 0,05 % et 0,08 %, des sanctions administratives s\'appliquent. Au-delà de 0,08 %, c\'est une infraction criminelle. / The legal alcohol limit in Quebec is 0.08%. Between 0.05% and 0.08%, administrative sanctions apply. Above 0.08%, it is a criminal offense.',
  },
  {
    id: 37,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Quelle est la principale différence entre un permis de classe 6A et un permis 6R ?',
    qEN: 'What is the main difference between a Class 6A and a Class 6R license?',
    options: [
      'La 6A permet les autoroutes, la 6R non',
      'La 6A est le permis complet, la 6R est le permis d\'apprenti',
      'La 6A est réservée aux grosses motos',
      'La 6A coûte plus cher à obtenir',
    ],
    optionsEN: [
      '6A allows highways, 6R does not',
      '6A is the full license, 6R is the learner permit',
      '6A is for large motorcycles only',
      '6A costs more to obtain',
    ],
    answer: 1,
    explanation: 'La classe 6R est le permis d\'apprenti avec des restrictions importantes. La classe 6A est le permis complet sans restrictions. Vous progressez de 6R à 6A après les étapes requises. / Class 6R is the learner permit with major restrictions. Class 6A is the full license with no restrictions. You progress from 6R to 6A after completing the required steps.',
  },
  {
    id: 38,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Vous roulez à 155 km/h sur une autoroute limitée à 100 km/h. Que risquez-vous ?',
    qEN: 'You drive at 155 km/h on a 100 km/h highway. What are the consequences?',
    options: [
      'Un simple excès de vitesse ordinaire',
      'Une conduite dangereuse avec saisie du véhicule',
      'Une perte de 3 points seulement',
      'Une infraction mineure sans conséquence',
    ],
    optionsEN: [
      'A simple ordinary speeding ticket',
      'Dangerous driving with vehicle seizure',
      'Only a 3-point loss',
      'A minor infraction with no major consequence',
    ],
    answer: 1,
    explanation: 'Dépasser la limite de 50 km/h ou plus est de la conduite dangereuse. Votre véhicule est saisi sur place et votre permis suspendu immédiatement pour 30 jours. / Exceeding the limit by 50 km/h or more is dangerous driving. Your vehicle is seized on the spot and your license is immediately suspended for 30 days.',
  },
  {
    id: 39,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Combien de temps dure la période d\'apprentissage avant d\'obtenir la classe 6A ?',
    qEN: 'How long is the learning period before obtaining a Class 6A license?',
    options: ['3 mois', '6 mois', '12 mois', '24 mois'],
    optionsEN: ['3 months', '6 months', '12 months', '24 months'],
    answer: 2,
    explanation: 'Après avoir réussi le cours de conduite reconnu, vous attendez 12 mois en classe 6R avant de passer votre examen de classe 6A sur route. / After completing an approved riding course, you wait 12 months with a Class 6R before taking your Class 6A road test.',
  },
  {
    id: 40,
    province: 'qc',
    category: 'Quebec Law',
    q: 'Quelle est la seule pièce d\'équipement obligatoire par loi pour conduire une moto au Québec ?',
    qEN: 'What is the only equipment required by law to ride a motorcycle in Quebec?',
    options: [
      'La veste de cuir avec armures',
      'Le casque homologué',
      'Les gants de protection',
      'Les bottes montantes',
    ],
    optionsEN: [
      'The leather jacket with armor',
      'The certified helmet',
      'The protective gloves',
      'The ankle-high boots',
    ],
    answer: 1,
    explanation: 'Seul le casque est obligatoire par la loi au Québec. Il doit être homologué et certifié. Les autres équipements sont très recommandés pour votre protection personnelle. / Only the helmet is legally required in Quebec. It must be certified. Other equipment is strongly recommended for your personal protection.',
  },

  // ============================================================
  // RIDING SCENARIOS / Scénarios de conduite — questions 41–50
  // ============================================================

  {
    id: 41,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Vous approchez une courbe et voyez des feuilles mouillées sur la chaussée. Que faites-vous ?',
    qEN: 'You approach a curve and see wet leaves on the road. What do you do?',
    options: [
      'Freinez fort dans la courbe',
      'Ralentissez avant la courbe, puis traversez en restant droit',
      'Accélérez pour passer rapidement',
      'Rien de spécial, continuez normalement',
    ],
    optionsEN: [
      'Brake hard inside the curve',
      'Slow down before the curve, then ride through it smoothly',
      'Speed up to get through quickly',
      'Nothing special, continue normally',
    ],
    answer: 1,
    explanation: 'Les feuilles mouillées sont extrêmement glissantes. Ralentissez avant d\'entrer dans la courbe pendant que vous êtes encore droit. Ne freinez jamais en pleine courbe. / Wet leaves are extremely slippery. Slow down before entering the curve while you are still upright. Never brake while in a turn.',
  },
  {
    id: 42,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Une portière de voiture s\'ouvre soudainement devant vous. Quelle est la meilleure réaction ?',
    qEN: 'A car door suddenly opens in front of you. What is your best reaction?',
    options: [
      'Freinez et tournez vers le trottoir à droite',
      'Klaxonnez et continuez à la même vitesse',
      'Déviez à gauche si la voie est libre',
      'Accélérez pour passer avant que la porte s\'ouvre complètement',
    ],
    optionsEN: [
      'Brake and turn toward the curb on the right',
      'Honk and continue at the same speed',
      'Swerve left if the lane is clear',
      'Speed up to pass before the door fully opens',
    ],
    answer: 2,
    explanation: 'Si une portière s\'ouvre, déviez vers la gauche si la voie est libre. Vérifiez d\'abord dans vos rétroviseurs. Klaxonnez pour avertir le conducteur. Roulez lentement près des voitures stationnées. / If a door opens, swerve left if the lane is clear. Check your mirrors first. Honk to warn the driver. Ride slowly when passing parked cars.',
  },
  {
    id: 43,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Vous voyez du gravier éparpillé au centre d\'un carrefour. Où vous positionnez-vous ?',
    qEN: 'You see gravel scattered in the center of an intersection. Where do you position yourself?',
    options: [
      'Au centre de votre voie comme d\'habitude',
      'Dans le gravier pour le balayer',
      'Là où l\'asphalte est propre, en évitant le gravier',
      'Sur la ligne de centre de la route',
    ],
    optionsEN: [
      'In the center of your lane as usual',
      'In the gravel to sweep it aside',
      'Where the asphalt is clean, avoiding the gravel',
      'On the road center line',
    ],
    answer: 2,
    explanation: 'Le gravier est très dangereux en moto. Positionnez-vous là où l\'asphalte est propre et sec. Réduisez votre vitesse. Soyez prêt à ajuster votre trajectoire. / Gravel is very dangerous on a motorcycle. Position yourself where the asphalt is clean and dry. Reduce your speed. Be ready to adjust your path.',
  },
  {
    id: 44,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Un chevreuil traverse soudainement la route devant vous. Que devez-vous faire ?',
    qEN: 'A deer suddenly crosses the road in front of you. What should you do?',
    options: [
      'Freinez brusquement et déviez à pleine vitesse',
      'Freinez progressivement et klaxonnez sans dévier brusquement',
      'Accélérez pour passer avant l\'animal',
      'Zigzaguez pour éviter l\'animal',
    ],
    optionsEN: [
      'Brake hard and swerve at full speed',
      'Brake progressively and honk without swerving suddenly',
      'Speed up to pass before the animal',
      'Zigzag to avoid the animal',
    ],
    answer: 1,
    explanation: 'Face à un animal, freinez progressivement et klaxonnez. Évitez de dévier brusquement car vous risquez de tomber. Les cervidés bougent de façon imprévisible. / When facing an animal, brake progressively and honk. Avoid sudden swerves as you risk falling. Deer move unpredictably.',
  },
  {
    id: 45,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Le soleil est directement dans vos yeux et vous distinguez mal la route. Que faites-vous ?',
    qEN: 'The sun is directly in your eyes and you can barely see the road. What do you do?',
    options: [
      'Accélérez pour sortir de la zone rapidement',
      'Baissez votre visière teintée et augmentez la distance de suivi',
      'Fermez les yeux quelques secondes',
      'Continuez comme d\'habitude',
    ],
    optionsEN: [
      'Speed up to exit the glare zone quickly',
      'Lower your tinted visor and increase following distance',
      'Close your eyes for a few seconds',
      'Continue as usual',
    ],
    answer: 1,
    explanation: 'Utilisez une visière teintée ou des lunettes de soleil. Augmentez votre distance de suivi car votre vision est réduite. Réduisez aussi votre vitesse si nécessaire. / Use a tinted visor or sunglasses. Increase your following distance because your vision is reduced. Also reduce your speed if necessary.',
  },
  {
    id: 46,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Vous roulez la nuit sur une route de campagne sans éclairage. Quel phare utilisez-vous ?',
    qEN: 'You ride at night on an unlit country road. Which headlight do you use?',
    options: [
      'Les feux de croisement seulement',
      'Les feux de route quand personne n\'arrive en face',
      'Aucun phare supplémentaire',
      'Les feux de détresse clignotants',
    ],
    optionsEN: [
      'Low beams only',
      'High beams when no oncoming traffic',
      'No extra lights',
      'Flashing hazard lights',
    ],
    answer: 1,
    explanation: 'Utilisez les feux de route la nuit quand aucun véhicule ne vient en sens inverse. Passez aux feux de croisement dès qu\'un véhicule approche pour ne pas l\'aveugler. / Use high beams at night when no vehicle is coming toward you. Switch to low beams as soon as a vehicle approaches to avoid blinding them.',
  },
  {
    id: 47,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Un véhicule vous colle de très près depuis plusieurs minutes. Quelle est la meilleure solution ?',
    qEN: 'A vehicle has been tailgating you closely for several minutes. What is the best solution?',
    options: [
      'Ralentissez brusquement pour l\'énerver',
      'Freinez fort pour l\'avertir',
      'Changez de voie ou laissez-le passer de façon sécuritaire',
      'Accélérez autant que possible',
    ],
    optionsEN: [
      'Brake suddenly to annoy them',
      'Brake hard to warn them',
      'Change lanes or let them pass safely',
      'Accelerate as much as possible',
    ],
    answer: 2,
    explanation: 'Laissez le véhicule agressif vous dépasser en changeant de voie ou en vous rangeant. Ne freinez jamais brusquement. Votre sécurité prime sur votre fierté. / Let the aggressive vehicle pass by changing lanes or pulling over. Never brake suddenly. Your safety matters more than your pride.',
  },
  {
    id: 48,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Vous arrivez à un carrefour avec un feu vert. Que vérifiez-vous avant d\'avancer ?',
    qEN: 'You arrive at an intersection with a green light. What do you check before proceeding?',
    options: [
      'Rien, le feu est vert',
      'Gauche, droite, puis gauche encore avant d\'avancer',
      'Seulement à gauche selon le sens du trafic',
      'Votre vitesse seulement',
    ],
    optionsEN: [
      'Nothing, the light is green',
      'Left, right, then left again before proceeding',
      'Only to the left since that is traffic flow',
      'Your speed only',
    ],
    answer: 1,
    explanation: 'Même avec un feu vert, vérifiez gauche-droite-gauche avant d\'avancer. Des conducteurs peuvent brûler le rouge. Un feu vert ne garantit pas que l\'intersection est libre. / Even with a green light, check left-right-left before proceeding. Drivers may run red lights. A green light does not guarantee the intersection is clear.',
  },
  {
    id: 49,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Vous approchez un passage à niveau. Comment traversez-vous les rails de façon sécuritaire ?',
    qEN: 'You approach a railway crossing. How do you cross the tracks safely?',
    options: [
      'En diagonale à haute vitesse',
      'À angle droit par rapport aux rails, à vitesse réduite',
      'En maintenant votre vitesse normale',
      'En évitant de freiner jusqu\'après les rails',
    ],
    optionsEN: [
      'Diagonally at high speed',
      'At a right angle to the tracks, at reduced speed',
      'While maintaining your normal speed',
      'While avoiding braking until after the tracks',
    ],
    answer: 1,
    explanation: 'Traversez les rails perpendiculairement pour éviter que votre roue glisse dans la rainure. Réduisez votre vitesse avant le passage. Les rails mouillés sont très glissants. / Cross tracks at a right angle to prevent your wheel from slipping into the groove. Reduce speed before the crossing. Wet rails are very slippery.',
  },
  {
    id: 50,
    province: 'qc',
    category: 'Riding Scenarios',
    q: 'Après deux heures sur l\'autoroute, vous commencez à vous sentir somnolent. Que faites-vous ?',
    qEN: 'After two hours on the highway, you start feeling drowsy. What do you do?',
    options: [
      'Continuez et ouvrez votre visière pour l\'air frais',
      'Prenez une sortie, arrêtez-vous et reposez-vous',
      'Buvez un café et continuez à grande vitesse',
      'Écoutez de la musique forte pour rester éveillé',
    ],
    optionsEN: [
      'Continue and open your visor for fresh air',
      'Take an exit, stop, and rest',
      'Drink coffee and continue at high speed',
      'Listen to loud music to stay awake',
    ],
    answer: 1,
    explanation: 'La somnolence est mortelle en moto. Prenez une sortie dès que possible. Dormez au minimum 20 minutes. L\'air frais et le café ne suffisent pas quand vous êtes vraiment somnolent. / Drowsiness is deadly on a motorcycle. Take an exit as soon as possible. Sleep for at least 20 minutes. Fresh air and coffee are not enough when you are truly drowsy.',
  },

];

// ============================================================
// GEAR CHECKLIST
// ============================================================

export interface GearItem {
  id: string;
  critical: boolean;
  nameFr: string;
  nameEn: string;
  descFr: string;
  descEn: string;
  icon: string;
}

export const gearItems: GearItem[] = [
  {
    id: 'helmet',
    critical: true,
    nameFr: 'Casque intégral homologué',
    nameEn: 'Approved Full-Face Helmet',
    descFr: 'Obligatoire par la loi. Le casque intégral protège la tête et le menton. Recherchez les certifications DOT, ECE 22.06 ou SNELL.',
    descEn: 'Mandatory by law. A full-face helmet protects the head and chin. Look for DOT, ECE 22.06 or SNELL certifications.',
    icon: '🪖',
  },
  {
    id: 'jacket',
    critical: true,
    nameFr: 'Veste de moto avec armures',
    nameEn: 'Motorcycle Jacket with Armor',
    descFr: 'Cuir ou textile avec armures aux épaules, coudes et dos. Protège contre l\'abrasion et les chocs en cas de chute.',
    descEn: 'Leather or textile with armor at shoulders, elbows and back. Protects against abrasion and impact in a fall.',
    icon: '🧥',
  },
  {
    id: 'gloves',
    critical: true,
    nameFr: 'Gants de moto',
    nameEn: 'Motorcycle Gloves',
    descFr: 'Les mains sont la première chose qu\'on tend lors d\'une chute. Gants avec armures aux paumes et articulations.',
    descEn: 'Hands are the first thing we extend in a fall. Gloves with palm and knuckle armor.',
    icon: '🧤',
  },
  {
    id: 'boots',
    critical: true,
    nameFr: 'Bottes de moto',
    nameEn: 'Motorcycle Boots',
    descFr: 'Protègent les chevilles et les pieds. Semelle antidérapante, renforts aux malléoles, fermeture sécurisée.',
    descEn: 'Protect ankles and feet. Non-slip sole, ankle reinforcements, secure closure.',
    icon: '👢',
  },
  {
    id: 'pants',
    critical: false,
    nameFr: 'Pantalon de moto avec armures',
    nameEn: 'Motorcycle Pants with Armor',
    descFr: 'Armures aux genoux et hanches. Cuir ou textile renforcé. Fortement recommandé pour protéger le bas du corps.',
    descEn: 'Knee and hip armor. Leather or reinforced textile. Highly recommended to protect the lower body.',
    icon: '👖',
  },
  {
    id: 'eyewear',
    critical: false,
    nameFr: 'Protection oculaire (lunettes/visière)',
    nameEn: 'Eye Protection (goggles/visor)',
    descFr: 'Requis si le casque est ouvert. Protège contre le vent, les insectes, les débris. Visière anti-UV recommandée.',
    descEn: 'Required if helmet is open-face. Protects against wind, insects, debris. Anti-UV visor recommended.',
    icon: '🥽',
  },
  {
    id: 'hiviz',
    critical: false,
    nameFr: 'Gilet ou vêtements haute visibilité',
    nameEn: 'High-Visibility Vest or Clothing',
    descFr: 'Améliore considérablement votre visibilité pour les autres conducteurs, surtout la nuit ou par mauvais temps.',
    descEn: 'Significantly improves your visibility to other drivers, especially at night or in bad weather.',
    icon: '🦺',
  },
  {
    id: 'earplugs',
    critical: false,
    nameFr: 'Bouchons d\'oreilles',
    nameEn: 'Ear Plugs',
    descFr: 'Le bruit du vent à haute vitesse peut causer des dommages auditifs permanents. Les bouchons réduisent la fatigue.',
    descEn: 'Wind noise at high speed can cause permanent hearing damage. Ear plugs reduce fatigue.',
    icon: '🔇',
  },
];

// ============================================================
// LICENSING STEPS
// ============================================================

export interface LicensingStep {
  id: string;
  province: Province;
  stepNumber: number;
  titleFr: string;
  titleEn: string;
  descFr: string;
  descEn: string;
}

export const licensingSteps: LicensingStep[] = [
  // Quebec steps
  {
    id: 'qc-step-1',
    province: 'qc',
    stepNumber: 1,
    titleFr: 'Réussir l\'examen théorique SAAQ',
    titleEn: 'Pass the SAAQ Theory Exam',
    descFr: 'Rendez-vous dans un point de service SAAQ. Étudiez le guide "Conduire une moto". Réussissez l\'examen de connaissance pour obtenir le permis apprenti conducteur de classe 6.',
    descEn: 'Visit a SAAQ service point. Study the "Operating a Motorcycle" guide. Pass the knowledge test to get the Class 6 learner\'s license.',
  },
  {
    id: 'qc-step-2',
    province: 'qc',
    stepNumber: 2,
    titleFr: 'Compléter un cours de conduite reconnu',
    titleEn: 'Complete an Approved Riding Course',
    descFr: 'Suivez un cours de conduite moto dans une école reconnue par la SAAQ (ex: Tecnic). Cela inclut la théorie, les manœuvres en espace fermé et la conduite sur route.',
    descEn: 'Complete a motorcycle course at a SAAQ-recognized school (e.g., Tecnic). This includes theory, closed-space maneuvers and road riding.',
  },
  {
    id: 'qc-step-3',
    province: 'qc',
    stepNumber: 3,
    titleFr: 'Période d\'apprentissage de 12 mois',
    titleEn: '12-Month Learning Period',
    descFr: 'Conduisez avec votre permis probatoire pendant au moins 12 mois. Respectez les restrictions : taux d\'alcool 0,00%, pas de passager les 6 premiers mois.',
    descEn: 'Ride with your probationary license for at least 12 months. Follow restrictions: 0.00% blood alcohol, no passenger for the first 6 months.',
  },
  {
    id: 'qc-step-4',
    province: 'qc',
    stepNumber: 4,
    titleFr: 'Examen de conduite sur route',
    titleEn: 'On-Road Driving Exam',
    descFr: 'Après 12 mois, prenez rendez-vous pour l\'examen de conduite sur route avec un examinateur SAAQ. Pratiquez les manœuvres d\'urgence et les virages.',
    descEn: 'After 12 months, schedule your on-road exam with a SAAQ examiner. Practice emergency maneuvers and cornering.',
  },
  {
    id: 'qc-step-5',
    province: 'qc',
    stepNumber: 5,
    titleFr: 'Obtenir le permis de classe 6 régulier',
    titleEn: 'Get Your Regular Class 6 License',
    descFr: 'Après avoir réussi l\'examen de conduite, vous obtenez le permis de classe 6 régulier. Bienvenue dans le monde des motocyclistes !',
    descEn: 'After passing the road test, you receive your regular Class 6 license. Welcome to the world of motorcyclists!',
  },
  // Ontario steps
  {
    id: 'on-step-1',
    province: 'on',
    stepNumber: 1,
    titleFr: 'Réussir le test écrit M1 au MTO',
    titleEn: 'Pass the M1 Written Test at MTO',
    descFr: 'Rendez-vous dans un centre DriveTest. Étudiez le Manuel du motocycliste de l\'Ontario. Réussissez l\'examen de vision et le test écrit pour obtenir le M1.',
    descEn: 'Visit a DriveTest centre. Study the Ontario Motorcycle Handbook. Pass the vision exam and written test to get your M1.',
  },
  {
    id: 'on-step-2',
    province: 'on',
    stepNumber: 2,
    titleFr: 'Pratiquer avec le permis M1 (90 jours)',
    titleEn: 'Practice with M1 License (90 Days)',
    descFr: 'Avec le M1, pratiquez pendant au moins 60 jours. Restrictions : pas de nuit, pas d\'autoroute, alcool 0,00%. Idéalement, suivez un cours de sécurité approuvé.',
    descEn: 'With M1, practice for at least 60 days. Restrictions: no night riding, no expressways, 0.00% alcohol. Ideally, take an approved safety course.',
  },
  {
    id: 'on-step-3',
    province: 'on',
    stepNumber: 3,
    titleFr: 'Passer le test M2 (conduite sur route)',
    titleEn: 'Take the M2 Road Test',
    descFr: 'Après 60 jours de M1, prenez rendez-vous pour le test M2. Les compétences testées incluent : démarrage, arrêts, virages, changements de voie, distance de suivi.',
    descEn: 'After 60 days of M1, schedule your M2 road test. Skills tested: starting, stopping, turning, lane changes, following distance.',
  },
  {
    id: 'on-step-4',
    province: 'on',
    stepNumber: 4,
    titleFr: 'Période M2 — 22 mois minimum',
    titleEn: 'M2 Period — Minimum 22 Months',
    descFr: 'Conduisez avec le M2 pendant au moins 22 mois (ou 12 mois si vous avez suivi un cours approuvé). Alcool 0,00% requis.',
    descEn: 'Ride with M2 for at least 22 months (or 12 months if you completed an approved course). 0.00% alcohol required.',
  },
  {
    id: 'on-step-5',
    province: 'on',
    stepNumber: 5,
    titleFr: 'Passer le test final M — Permis complet',
    titleEn: 'Pass the Final M Test — Full License',
    descFr: 'Le test M final est plus exigeant : il inclut des manœuvres d\'urgence, freinage d\'urgence, et conduite sur route à vitesse normale. Réussissez pour obtenir le M complet.',
    descEn: 'The final M test is more demanding: it includes emergency maneuvers, emergency braking, and road riding at normal speeds. Pass to get your full M license.',
  },
];
